language: cpp
git:
  depth: false

os:
  - linux
  - osx

compiler:
  - clang
 
addons:
  homebrew:
    packages:
    - llvm

script: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/llvm/bin:$PATH" ; fi
  - make release
  - ./odin run examples/demo/demo.odin
  - ./odin check examples/demo/demo.odin -vet

notifications:
  email: false
