image: 
  - Visual Studio 2017
shallow_clone: true

platform: x64

install:
  - cd bin
  - appveyor DownloadFile https://github.com/odin-lang/Odin/releases/download/llvm-windows/llvm-binaries.zip
  - 7z x llvm-binaries.zip > nul
  - cd ..

build_script: 
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - ./build_ci.bat

test_script:
  - odin run examples/demo/demo.odin
  - odin check examples/demo/demo.odin -vet