package test_core_x509

// Fixtures generated with openssl 3.x (see testdata/):
//
//   openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
//     -subj "/C=US/O=Odin Test/CN=localhost" \
//     -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
//     -addext "basicConstraints=critical,CA:TRUE"
//
//   openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 \
//     -sha256 -days 3650 -nodes -subj "/CN=example.com" \
//     -addext "subjectAltName=DNS:example.com,DNS:*.example.com,IP:2001:db8::1" \
//     -addext "extendedKeyUsage=serverAuth" \
//     -addext "keyUsage=critical,digitalSignature" \
//     -addext "basicConstraints=critical,CA:FALSE"
//
//   openssl req -x509 -newkey ed25519 -days 3650 -nodes -subj "/CN=ed.test"
//
// Field expectations below were cross-checked against
// `openssl x509 -noout -text`.

import "core:crypto/hash"
import "core:crypto/x509"
import "core:testing"
import "core:time"

RSA_DER := #load("testdata/rsa.der")
EC_DER := #load("testdata/ec.der")
ED_DER := #load("testdata/ed.der")

// Self-signed RSA-PSS CA (SHA-256, MGF1-SHA-256, salt 32), generated with:
//   openssl req -x509 -newkey rsa:2048 -nodes -sha256 -days 3650 \
//     -subj "/CN=pss.rsa.test" -sigopt rsa_padding_mode:pss \
//     -sigopt rsa_pss_saltlen:32 -addext "basicConstraints=critical,CA:TRUE"
PSS_DER := #load("testdata/pss.der")

// Chains for verify_chain (generated by testdata/gen_chains.sh):
//   P-256: chain_ec_root -> chain_ec_inter (pathlen:0) -> chain_ec_leaf
//          (CN=leaf.example.com, EKU serverAuth); chain_ec_other_root is
//          an unrelated anchor for the wrong-root case.
//   Ed25519: chain_ed_root -> chain_ed_leaf (CN=ed-leaf.example.com).
EC_CHAIN_ROOT  := #load("testdata/chain_ec_root.der")
EC_CHAIN_INTER := #load("testdata/chain_ec_inter.der")
EC_CHAIN_LEAF  := #load("testdata/chain_ec_leaf.der")
EC_OTHER_ROOT  := #load("testdata/chain_ec_other_root.der")
ED_CHAIN_ROOT  := #load("testdata/chain_ed_root.der")
ED_CHAIN_LEAF  := #load("testdata/chain_ed_leaf.der")
// Expired root (validity 2010-2015) that signed a still-valid leaf;
// RFC 5280 section 6.1 does not validate the trust anchor itself.
EC_EXPIRED_ROOT := #load("testdata/chain_ec_expired_root.der")
EC_EXP_LEAF     := #load("testdata/chain_ec_expleaf.der")

// Negative path-validation fixtures: each chain trips one verify_chain
// rejection. neg_root signs the *_inter certs; pl_a -> pl_b -> pl_leaf
// chains deeper to violate pathlen:0 on pl_a.
NEG_ROOT          := #load("testdata/neg_root.der")
NEG_NOKCS_INTER   := #load("testdata/neg_nokcs_inter.der")   // CA, no keyCertSign
NEG_NOKCS_LEAF    := #load("testdata/neg_nokcs_leaf.der")
NEG_NOTCA_INTER   := #load("testdata/neg_notca_inter.der")   // CA:FALSE
NEG_NOTCA_LEAF    := #load("testdata/neg_notca_leaf.der")
NEG_EXPINTER      := #load("testdata/neg_expinter_inter.der") // expired CA
NEG_EXPINTER_LEAF := #load("testdata/neg_expinter_leaf.der")
NEG_PL_A          := #load("testdata/neg_pl_a.der")           // pathlen:0
NEG_PL_B          := #load("testdata/neg_pl_b.der")
NEG_PL_LEAF       := #load("testdata/neg_pl_leaf.der")
NEG_EKU_INTER     := #load("testdata/neg_eku_inter.der")      // emailProtection CA
NEG_EKU_LEAF      := #load("testdata/neg_eku_leaf.der")       // serverAuth leaf
NEG_NC_INTER      := #load("testdata/neg_nc_inter.der")       // non-critical nameConstraints
NEG_NC_LEAF       := #load("testdata/neg_nc_leaf.der")        // name within permitted subtree
// Dedicated name-constraint chains (EC P-256), generated with openssl:
//   root -> nc_inter (critical NC: permitted DNS:.example.com, IP:10.0.0.0/8)
//     -> nc_leaf_ok  (SAN host.example.com + 10.1.2.3 — within → accept)
//     -> nc_leaf_bad (SAN host.evil.com — outside → reject)
//   root -> nc_dir_inter (critical NC on directoryName — a form we do not
//     evaluate) -> nc_leaf_dir (must fail closed → reject)
NC_ROOT      := #load("testdata/nc_root.der")
NC_INTER     := #load("testdata/nc_inter.der")
NC_DIR_INTER := #load("testdata/nc_dir_inter.der")
NC_LEAF_OK   := #load("testdata/nc_leaf_ok.der")
NC_LEAF_BAD  := #load("testdata/nc_leaf_bad.der")
NC_LEAF_DIR  := #load("testdata/nc_leaf_dir.der")
// CVE-2025-61727 shape: nc_excl_inter excludes DNS:bar.example.com; the leaf's
// wildcard SAN *.example.com spans bar.example.com and must be rejected, not
// treated as a literal string that slips past the exclusion.
NC_EXCL_INTER := #load("testdata/nc_excl_inter.der")
NC_LEAF_WILD  := #load("testdata/nc_leaf_wild.der")
// EKU alternative path: two intermediates sharing a subject DN and key,
// one emailProtection-only, one serverAuth; the leaf chains through either.
EKU_ALT_BAD       := #load("testdata/eku_alt_bad.der")        // same key, emailProtection only
EKU_ALT_GOOD      := #load("testdata/eku_alt_good.der")       // same key, serverAuth
EKU_ALT_LEAF      := #load("testdata/eku_alt_leaf.der")       // serverAuth leaf
// Cross-signed cycle: A and B mutually cross-certify; trusting neither
// must terminate (no hang) and report Unknown_Authority.
CYC_A             := #load("testdata/cyc_a.der")
CYC_B             := #load("testdata/cyc_b.der")
CYC_A_BY_B        := #load("testdata/cyc_a_by_b.der")
CYC_B_BY_A        := #load("testdata/cyc_b_by_a.der")
CYC_LEAF          := #load("testdata/cyc_leaf.der")

// Reference times relative to the chain fixtures (issued 2026-06-13,
// leaves valid ~10 years). 2027 is inside every window; 2020 precedes
// the leaf; 2040 is past the leaf (which expires first).
CHAIN_NOW    :: i64(1798761600) // 2027-01-01Z
CHAIN_BEFORE :: i64(1577836800) // 2020-01-01Z
CHAIN_AFTER  :: i64(2208988800) // 2040-01-01Z

// A real CA root (GoDaddy G2) carrying serial number 0 — a
// non-conformant but in-the-wild case surfaced by differential testing
// against Go's crypto/x509 over the system CA store.
SERIAL_ZERO_DER := #load("testdata/serial_zero.der")

// A cert with two subjectAltName extensions, from the x509-limbo
// corpus — RFC 5280 section 4.2 forbids duplicate extension OIDs.
DUP_EXTENSION_DER := #load("testdata/dup_extension.der")

@(test)
test_duplicate_extension :: proc(t: ^testing.T) {
	cert, err := x509.parse(DUP_EXTENSION_DER)
	if err == .None {
		x509.destroy(&cert)
	}
	testing.expect_value(t, err, x509.Error.Duplicate_Extension)
}

@(test)
test_parse_rsa :: proc(t: ^testing.T) {
	cert, err := x509.parse(RSA_DER)
	defer x509.destroy(&cert)
	testing.expect_value(t, err, x509.Error.None)

	testing.expect_value(t, cert.version, 3)
	testing.expect_value(t, cert.signature_algorithm, x509.Signature_Algorithm.RSA_SHA256)
	testing.expect_value(t, cert.public_key_algorithm, x509.Public_Key_Algorithm.RSA)

	// serial=074476066FA3819E72A324BC52CEF3920F0E7156 (20 octets).
	testing.expect_value(t, len(cert.serial), 20)
	testing.expect_value(t, cert.serial[0], u8(0x07))
	testing.expect_value(t, cert.serial[19], u8(0x56))

	// 2048-bit modulus, e = 65537.
	testing.expect_value(t, len(cert.rsa_n), 256)
	testing.expect_value(t, len(cert.rsa_e), 3)
	testing.expect_value(t, cert.rsa_e[0], u8(0x01))
	testing.expect_value(t, cert.rsa_e[2], u8(0x01))

	// notBefore=Jun 12 18:53:09 2026 GMT.
	testing.expect_value(t, time.to_unix_seconds(cert.not_before), i64(1781290389))

	testing.expect_value(t, cert.basic_constraints_valid, true)
	testing.expect_value(t, cert.is_ca, true)
	testing.expect_value(t, cert.max_path_len, -1)

	testing.expect_value(t, len(cert.dns_names), 1)
	testing.expect_value(t, cert.dns_names[0], "localhost")
	testing.expect_value(t, len(cert.ip_addresses), 1)
	testing.expect_value(t, len(cert.ip_addresses[0]), 4)
	testing.expect_value(t, cert.ip_addresses[0][0], u8(127))

	// Self-signed: issuer bytes == subject bytes.
	testing.expect(t, len(cert.raw_issuer) > 0)
	testing.expect_value(t, string(cert.raw_issuer), string(cert.raw_subject))

	// openssl always adds SKI; self-signed adds matching AKI.
	testing.expect(t, len(cert.subject_key_id) > 0, "SKI expected")
	testing.expect(t, !cert.unhandled_critical, "all criticals understood")

	// The raw views must cover real ranges.
	testing.expect_value(t, len(cert.raw), len(RSA_DER))
	testing.expect(t, len(cert.raw_tbs) > 0)
	testing.expect(t, len(cert.raw_spki) > 0)
	testing.expect_value(t, len(cert.signature), 256)
}

@(test)
test_parse_ec :: proc(t: ^testing.T) {
	cert, err := x509.parse(EC_DER)
	defer x509.destroy(&cert)
	testing.expect_value(t, err, x509.Error.None)

	testing.expect_value(t, cert.signature_algorithm, x509.Signature_Algorithm.ECDSA_SHA256)
	testing.expect_value(t, cert.public_key_algorithm, x509.Public_Key_Algorithm.ECDSA_P256)
	testing.expect_value(t, len(cert.ec_point), 65)
	testing.expect_value(t, cert.ec_point[0], u8(0x04))

	testing.expect_value(t, time.to_unix_seconds(cert.not_after), i64(2096650389)) // notAfter Jun 9 18:53:09 2036 GMT

	testing.expect_value(t, cert.basic_constraints_valid, true)
	testing.expect_value(t, cert.is_ca, false)

	testing.expect_value(t, cert.has_key_usage, true)
	testing.expect(t, .Digital_Signature in cert.key_usage)
	testing.expect(t, .Key_Cert_Sign not_in cert.key_usage)

	testing.expect_value(t, cert.has_ext_key_usage, true)
	testing.expect(t, .Server_Auth in cert.ext_key_usage)
	testing.expect(t, .Client_Auth not_in cert.ext_key_usage)
	testing.expect_value(t, cert.eku_has_unknown, false)

	testing.expect_value(t, len(cert.dns_names), 2)
	testing.expect_value(t, cert.dns_names[0], "example.com")
	testing.expect_value(t, cert.dns_names[1], "*.example.com")
	testing.expect_value(t, len(cert.ip_addresses), 1)
	testing.expect_value(t, len(cert.ip_addresses[0]), 16)
	testing.expect_value(t, cert.ip_addresses[0][0], u8(0x20))
	testing.expect_value(t, cert.ip_addresses[0][1], u8(0x01))
}

@(test)
test_parse_ed25519 :: proc(t: ^testing.T) {
	cert, err := x509.parse(ED_DER)
	defer x509.destroy(&cert)
	testing.expect_value(t, err, x509.Error.None)

	testing.expect_value(t, cert.signature_algorithm, x509.Signature_Algorithm.Ed25519)
	testing.expect_value(t, cert.public_key_algorithm, x509.Public_Key_Algorithm.Ed25519)
	testing.expect_value(t, len(cert.ec_point), 32)
	testing.expect_value(t, len(cert.signature), 64)
}

// Serial 0 decodes to the single octet {0x00}, not empty (the
// openssl-aligned convention; see Certificate.serial).
@(test)
test_serial_zero :: proc(t: ^testing.T) {
	cert, err := x509.parse(SERIAL_ZERO_DER)
	defer x509.destroy(&cert)
	testing.expect_value(t, err, x509.Error.None)
	testing.expect_value(t, len(cert.serial), 1)
	testing.expect_value(t, cert.serial[0], u8(0x00))
	testing.expect_value(t, cert.is_ca, true)
}

@(test)
test_valid_at :: proc(t: ^testing.T) {
	cert, err := x509.parse(RSA_DER)
	defer x509.destroy(&cert)
	testing.expect_value(t, err, x509.Error.None)

	INSIDE := time.unix(1893456000, 0) // 2030-01-01Z
	BEFORE := time.unix(1577836800, 0) // 2020-01-01Z
	AFTER  := time.unix(2208988800, 0) // 2040-01-01Z
	testing.expect_value(t, x509.valid_at(&cert, INSIDE), true)
	testing.expect_value(t, x509.valid_at(&cert, BEFORE), false)
	testing.expect_value(t, x509.valid_at(&cert, AFTER), false)
	// Boundaries are inclusive.
	testing.expect_value(t, x509.valid_at(&cert, cert.not_before), true)
	testing.expect_value(t, x509.valid_at(&cert, cert.not_after), true)
}

@(test)
test_verify_hostname :: proc(t: ^testing.T) {
	ec, err := x509.parse(EC_DER)
	defer x509.destroy(&ec)
	testing.expect_value(t, err, x509.Error.None)

	// Exact and case-insensitive.
	testing.expect_value(t, x509.verify_hostname(&ec, "example.com"), x509.Error.None)
	testing.expect_value(t, x509.verify_hostname(&ec, "EXAMPLE.COM"), x509.Error.None)
	testing.expect_value(t, x509.verify_hostname(&ec, "example.com."), x509.Error.None)

	// Wildcard: exactly one left-most label.
	testing.expect_value(t, x509.verify_hostname(&ec, "api.example.com"), x509.Error.None)
	testing.expect_value(t, x509.verify_hostname(&ec, "API.Example.Com"), x509.Error.None)
	testing.expect_value(t, x509.verify_hostname(&ec, "a.b.example.com"), x509.Error.Hostname_Mismatch)
	testing.expect_value(t, x509.verify_hostname(&ec, "example.org"), x509.Error.Hostname_Mismatch)
	testing.expect_value(t, x509.verify_hostname(&ec, "com"), x509.Error.Hostname_Mismatch)

	// IPv6 SAN 2001:db8::1.
	testing.expect_value(t, x509.verify_hostname(&ec, "2001:db8::1"), x509.Error.None)
	testing.expect_value(t, x509.verify_hostname(&ec, "2001:db8::2"), x509.Error.Hostname_Mismatch)

	// IPv4 against the RSA cert (127.0.0.1 SAN).
	rsa, rerr := x509.parse(RSA_DER)
	defer x509.destroy(&rsa)
	testing.expect_value(t, rerr, x509.Error.None)
	testing.expect_value(t, x509.verify_hostname(&rsa, "127.0.0.1"), x509.Error.None)
	testing.expect_value(t, x509.verify_hostname(&rsa, "127.0.0.2"), x509.Error.Hostname_Mismatch)
	testing.expect_value(t, x509.verify_hostname(&rsa, "localhost"), x509.Error.None)

	// Ed cert has no SANs at all.
	ed, eerr := x509.parse(ED_DER)
	defer x509.destroy(&ed)
	testing.expect_value(t, eerr, x509.Error.None)
	testing.expect_value(t, x509.verify_hostname(&ed, "ed.test"), x509.Error.No_SAN)
}

// verify_hostname must accept any bytes in the host string and return a
// result (never fault), whatever odd punctuation the input contains. In
// normal use the host comes from the application, not the certificate;
// this just pins down robust behaviour on unusual inputs.
@(test)
test_verify_hostname_hostile_input :: proc(t: ^testing.T) {
	ec, err := x509.parse(EC_DER)
	defer x509.destroy(&ec)
	testing.expect_value(t, err, x509.Error.None)

	hostile := []string{
		"]:80",
		"]:",
		"]",
		"[",
		"[]",
		"::::",
		":",
		"]:a]:b",
		"\x00\x01\x02",
		"foo]:bar",
		"[not-closed",
		"*.*.*",
	}
	for h in hostile {
		// Any result is acceptable; not panicking is the point.
		_ = x509.verify_hostname(&ec, h)
	}
}

// Every truncation of a real certificate must fail cleanly.
@(test)
test_truncation_sweep :: proc(t: ^testing.T) {
	for n in 0 ..< len(EC_DER) {
		cert, err := x509.parse(EC_DER[:n])
		if err == .None {
			x509.destroy(&cert)
		}
		testing.expect(t, err != .None, "truncated certificate must be rejected")
	}
	// Trailing garbage is rejected too.
	{
		grown := make([]byte, len(EC_DER) + 1)
		defer delete(grown)
		copy(grown, EC_DER)
		_, err := x509.parse(grown)
		testing.expect(t, err != .None, "trailing bytes must be rejected")
	}
}

// ---- signature & chain verification ----

@(test)
test_verify_signature_ec :: proc(t: ^testing.T) {
	leaf, e1 := x509.parse(EC_CHAIN_LEAF);   defer x509.destroy(&leaf)
	inter, e2 := x509.parse(EC_CHAIN_INTER); defer x509.destroy(&inter)
	root, e3 := x509.parse(EC_CHAIN_ROOT);   defer x509.destroy(&root)
	testing.expect_value(t, e1, x509.Error.None)
	testing.expect_value(t, e2, x509.Error.None)
	testing.expect_value(t, e3, x509.Error.None)

	// Correct issuers verify; cross-pairings do not.
	testing.expect_value(t, x509.verify_signature(&leaf, &inter), x509.Error.None)
	testing.expect_value(t, x509.verify_signature(&inter, &root), x509.Error.None)
	testing.expect_value(t, x509.verify_signature(&leaf, &root), x509.Error.Signature_Invalid)
}

@(test)
test_verify_signature_ed :: proc(t: ^testing.T) {
	leaf, e1 := x509.parse(ED_CHAIN_LEAF); defer x509.destroy(&leaf)
	root, e2 := x509.parse(ED_CHAIN_ROOT); defer x509.destroy(&root)
	testing.expect_value(t, e1, x509.Error.None)
	testing.expect_value(t, e2, x509.Error.None)
	testing.expect_value(t, x509.verify_signature(&leaf, &root), x509.Error.None)
}

// RSA PKCS#1 v1.5 verification is wired through to core:crypto/rsa. rsa.der is
// a self-signed RSA-SHA256 CA, so it is its own issuer and its signature must
// verify; pairing an RSA-signed cert with a non-RSA issuer key is unsupported.
@(test)
test_verify_signature_rsa :: proc(t: ^testing.T) {
	rsa, e1 := x509.parse(RSA_DER); defer x509.destroy(&rsa)
	ec, e2 := x509.parse(EC_DER); defer x509.destroy(&ec)
	testing.expect_value(t, e1, x509.Error.None)
	testing.expect_value(t, e2, x509.Error.None)
	testing.expect_value(t, x509.verify_signature(&rsa, &rsa), x509.Error.None)
	testing.expect_value(t, x509.verify_signature(&rsa, &ec), x509.Error.Unsupported_Algorithm)
}

// RSA-PSS end-to-end: the parser decodes RSASSA-PSS-params (hash, MGF, salt)
// off the signatureAlgorithm, and verify_signature feeds them to
// rsa.verify_pss. pss.der is a self-signed RSA-PSS CA, so it is its own issuer.
@(test)
test_verify_signature_rsa_pss :: proc(t: ^testing.T) {
	pss, err := x509.parse(PSS_DER); defer x509.destroy(&pss)
	testing.expect_value(t, err, x509.Error.None)
	testing.expect_value(t, pss.signature_algorithm, x509.Signature_Algorithm.RSA_PSS)
	// Decoded parameters (SHA-256, MGF1-SHA-256, salt length 32).
	testing.expect_value(t, pss.pss_hash, hash.Algorithm.SHA256)
	testing.expect_value(t, pss.pss_mgf_hash, hash.Algorithm.SHA256)
	testing.expect_value(t, pss.pss_salt_len, 32)
	// The PSS signature verifies against the embedded key.
	testing.expect_value(t, x509.verify_signature(&pss, &pss), x509.Error.None)
}

@(test)
test_verify_chain_ec :: proc(t: ^testing.T) {
	leaf, e1 := x509.parse(EC_CHAIN_LEAF);   defer x509.destroy(&leaf)
	inter, e2 := x509.parse(EC_CHAIN_INTER); defer x509.destroy(&inter)
	root, e3 := x509.parse(EC_CHAIN_ROOT);   defer x509.destroy(&root)
	testing.expect_value(t, e1, x509.Error.None)
	testing.expect_value(t, e2, x509.Error.None)
	testing.expect_value(t, e3, x509.Error.None)

	opts := x509.Verify_Options{
		roots         = {&root},
		intermediates = {&inter},
		current_time  = time.unix(CHAIN_NOW, 0),
		dns_name      = "leaf.example.com",
		required_eku  = .Server_Auth,
	}
	chain, err := x509.verify_chain(&leaf, opts)
	defer delete(chain)
	testing.expect_value(t, err, x509.Error.None)
	testing.expect_value(t, len(chain), 3)
	if len(chain) == 3 {
		testing.expect(t, chain[0] == &leaf, "chain[0] is the leaf")
		testing.expect(t, chain[1] == &inter, "chain[1] is the intermediate")
		testing.expect(t, chain[2] == &root, "chain[2] is the anchor")
	}
}

@(test)
test_verify_chain_ed :: proc(t: ^testing.T) {
	leaf, e1 := x509.parse(ED_CHAIN_LEAF); defer x509.destroy(&leaf)
	root, e2 := x509.parse(ED_CHAIN_ROOT); defer x509.destroy(&root)
	testing.expect_value(t, e1, x509.Error.None)
	testing.expect_value(t, e2, x509.Error.None)

	opts := x509.Verify_Options{
		roots        = {&root},
		current_time = time.unix(CHAIN_NOW, 0),
		dns_name     = "ed-leaf.example.com",
	}
	chain, err := x509.verify_chain(&leaf, opts)
	defer delete(chain)
	testing.expect_value(t, err, x509.Error.None)
	testing.expect_value(t, len(chain), 2)
}

@(test)
test_verify_chain_negatives :: proc(t: ^testing.T) {
	leaf, _  := x509.parse(EC_CHAIN_LEAF);   defer x509.destroy(&leaf)
	inter, _ := x509.parse(EC_CHAIN_INTER);  defer x509.destroy(&inter)
	root, _  := x509.parse(EC_CHAIN_ROOT);   defer x509.destroy(&root)
	other, _ := x509.parse(EC_OTHER_ROOT);   defer x509.destroy(&other)

	roots  := []^x509.Certificate{&root}
	inters := []^x509.Certificate{&inter}

	// Missing the intermediate: cannot bridge leaf -> root.
	{
		opts := x509.Verify_Options{roots = roots, current_time = time.unix(CHAIN_NOW, 0)}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Unknown_Authority)
	}
	// Untrusted anchor.
	{
		opts := x509.Verify_Options{roots = {&other}, intermediates = inters, current_time = time.unix(CHAIN_NOW, 0)}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Unknown_Authority)
	}
	// Expired (now is past the leaf's notAfter).
	{
		opts := x509.Verify_Options{roots = roots, intermediates = inters, current_time = time.unix(CHAIN_AFTER, 0)}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Expired)
	}
	// Not yet valid (now precedes the leaf's notBefore).
	{
		opts := x509.Verify_Options{roots = roots, intermediates = inters, current_time = time.unix(CHAIN_BEFORE, 0)}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Not_Yet_Valid)
	}
	// Hostname mismatch on an otherwise-valid chain.
	{
		opts := x509.Verify_Options{roots = roots, intermediates = inters, current_time = time.unix(CHAIN_NOW, 0), dns_name = "wrong.example.com"}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Hostname_Mismatch)
	}
	// Required EKU the leaf does not carry (it has serverAuth only).
	{
		opts := x509.Verify_Options{roots = roots, intermediates = inters, current_time = time.unix(CHAIN_NOW, 0), required_eku = .Client_Auth}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Incompatible_Usage)
	}
}

// The trust anchor is validated like any issuer (matching Go/OpenSSL):
// an expired root is rejected, so a chain whose only anchor is expired
// fails to build. (Resilience to expired roots comes from offering an
// alternate valid anchor, not from skipping the check.)
@(test)
test_verify_chain_expired_anchor_rejected :: proc(t: ^testing.T) {
	leaf, e1 := x509.parse(EC_EXP_LEAF);       defer x509.destroy(&leaf)
	root, e2 := x509.parse(EC_EXPIRED_ROOT);   defer x509.destroy(&root)
	testing.expect_value(t, e1, x509.Error.None)
	testing.expect_value(t, e2, x509.Error.None)

	// Sanity: the anchor really is expired at CHAIN_NOW.
	testing.expect_value(t, x509.valid_at(&root, time.unix(CHAIN_NOW, 0)), false)

	opts := x509.Verify_Options{roots = {&root}, current_time = time.unix(CHAIN_NOW, 0)}
	chain, err := x509.verify_chain(&leaf, opts)
	defer delete(chain)
	testing.expect_value(t, err, x509.Error.Unknown_Authority)
}

// EKU nesting (surfaced by x509-limbo): an intermediate constrained to
// emailProtection must not be usable to issue a serverAuth leaf when the
// caller requires serverAuth. Without an EKU requirement the chain still
// builds (EKU is unconstrained).
@(test)
test_verify_chain_eku_nesting :: proc(t: ^testing.T) {
	root, _  := x509.parse(NEG_ROOT);       defer x509.destroy(&root)
	inter, _ := x509.parse(NEG_EKU_INTER);  defer x509.destroy(&inter)
	leaf, _  := x509.parse(NEG_EKU_LEAF);   defer x509.destroy(&leaf)
	now := time.unix(CHAIN_NOW, 0)

	// No EKU requirement: the email-only intermediate does not block it.
	{
		opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = now}
		c, err := x509.verify_chain(&leaf, opts)
		defer delete(c)
		testing.expect_value(t, err, x509.Error.None)
		testing.expect_value(t, len(c), 3)
	}
	// Requiring serverAuth: the intermediate's emailProtection-only EKU
	// forbids it, so the path is rejected.
	{
		opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = now, required_eku = .Server_Auth}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Incompatible_Usage)
	}
}

// EKU nesting must be enforced DURING path-building The two intermediates
// share a subject DN and key (so the leaf signature-verifies through
// either), differing only in EKU, and we offer them in BOTH orders, the
// result must be the same successful chain regardless of ordering.
@(test)
test_verify_chain_eku_alt_path :: proc(t: ^testing.T) {
	root, _ := x509.parse(NEG_ROOT);      defer x509.destroy(&root)
	bad, _  := x509.parse(EKU_ALT_BAD);   defer x509.destroy(&bad)
	good, _ := x509.parse(EKU_ALT_GOOD);  defer x509.destroy(&good)
	leaf, _ := x509.parse(EKU_ALT_LEAF);  defer x509.destroy(&leaf)
	now := time.unix(CHAIN_NOW, 0)

	// emailProtection-only intermediate offered first:
	{
		opts := x509.Verify_Options{
			roots         = {&root},
			intermediates = {&bad, &good},
			current_time  = now,
			required_eku  = .Server_Auth,
		}
		c, err := x509.verify_chain(&leaf, opts)
		defer delete(c)
		testing.expect_value(t, err, x509.Error.None)
		testing.expect_value(t, len(c), 3)
		if len(c) == 3 {
			testing.expect(t, c[1] == &good, "must select the serverAuth-permitting intermediate")
		}
	}
	// serverAuth intermediate offered first: same successful result.
	{
		opts := x509.Verify_Options{
			roots         = {&root},
			intermediates = {&good, &bad},
			current_time  = now,
			required_eku  = .Server_Auth,
		}
		c, err := x509.verify_chain(&leaf, opts)
		defer delete(c)
		testing.expect_value(t, err, x509.Error.None)
		testing.expect_value(t, len(c), 3)
		if len(c) == 3 {
			testing.expect(t, c[1] == &good, "must select the serverAuth-permitting intermediate")
		}
	}
}

// Name constraints (RFC 5280 4.2.1.10) are enforced for dNSName and iPAddress:
// a leaf whose SANs fall within a constraining CA's permitted subtrees is
// accepted, one that falls outside is rejected, and a critical NameConstraints
// must NOT be mistaken for an unhandled critical extension.
@(test)
test_verify_chain_name_constraints_permitted :: proc(t: ^testing.T) {
	root, _  := x509.parse(NC_ROOT);     defer x509.destroy(&root)
	inter, _ := x509.parse(NC_INTER);    defer x509.destroy(&inter)
	leaf, _  := x509.parse(NC_LEAF_OK);  defer x509.destroy(&leaf)
	testing.expect(t, !inter.unhandled_critical, "critical NC is recognized, not unhandled")

	opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = time.unix(CHAIN_NOW, 0)}
	c, err := x509.verify_chain(&leaf, opts); defer delete(c)
	testing.expect_value(t, err, x509.Error.None) // host.example.com + 10.1.2.3 are permitted
	testing.expect_value(t, len(c), 3)
}

// A SAN outside every permitted subtree (host.evil.com vs permitted
// .example.com) must be rejected.
@(test)
test_verify_chain_name_constraints_violation :: proc(t: ^testing.T) {
	root, _  := x509.parse(NC_ROOT);      defer x509.destroy(&root)
	inter, _ := x509.parse(NC_INTER);     defer x509.destroy(&inter)
	leaf, _  := x509.parse(NC_LEAF_BAD);  defer x509.destroy(&leaf)

	opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = time.unix(CHAIN_NOW, 0)}
	c, err := x509.verify_chain(&leaf, opts); delete(c)
	testing.expect_value(t, err, x509.Error.Unknown_Authority)
}

// CVE-2025-61727: a wildcard SAN must not slip past a dNSName exclusion. The
// intermediate excludes bar.example.com; the leaf's *.example.com spans it, so
// the chain must be rejected (matching a wildcard as a literal string would
// wrongly accept it).
@(test)
test_verify_chain_name_constraints_wildcard_excluded :: proc(t: ^testing.T) {
	root, _  := x509.parse(NC_ROOT);        defer x509.destroy(&root)
	inter, _ := x509.parse(NC_EXCL_INTER);  defer x509.destroy(&inter)
	leaf, _  := x509.parse(NC_LEAF_WILD);   defer x509.destroy(&leaf)

	opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = time.unix(CHAIN_NOW, 0)}
	c, err := x509.verify_chain(&leaf, opts); delete(c)
	testing.expect_value(t, err, x509.Error.Unknown_Authority)
}

// A constraint on a GeneralName form we do not evaluate (here directoryName)
// must fail closed — reject rather than silently ignore the constraint.
@(test)
test_verify_chain_name_constraints_unevaluable_fail_closed :: proc(t: ^testing.T) {
	root, _  := x509.parse(NC_ROOT);        defer x509.destroy(&root)
	inter, _ := x509.parse(NC_DIR_INTER);   defer x509.destroy(&inter)
	leaf, _  := x509.parse(NC_LEAF_DIR);    defer x509.destroy(&leaf)

	opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = time.unix(CHAIN_NOW, 0)}
	c, err := x509.verify_chain(&leaf, opts); delete(c)
	testing.expect_value(t, err, x509.Error.Unknown_Authority)
}

// A mutually cross-signed CA cycle (neither anchor trusted) must not
// hang the path search: the cycle/depth/signature-budget bounds make it
// terminate with Unknown_Authority. If this test ever hangs rather than
// failing, the search lost its bound. (CVE-2024-0567 shape.)
@(test)
test_verify_chain_cross_signed_cycle :: proc(t: ^testing.T) {
	a, _      := x509.parse(CYC_A);       defer x509.destroy(&a)
	b, _      := x509.parse(CYC_B);       defer x509.destroy(&b)
	a_by_b, _ := x509.parse(CYC_A_BY_B);  defer x509.destroy(&a_by_b)
	b_by_a, _ := x509.parse(CYC_B_BY_A);  defer x509.destroy(&b_by_a)
	leaf, _   := x509.parse(CYC_LEAF);    defer x509.destroy(&leaf)

	// Every cross-cert and self-signed CA is offered as an intermediate;
	// no trust anchor is supplied, so the loop can never terminate at a
	// root.
	opts := x509.Verify_Options{
		intermediates = {&a, &b, &a_by_b, &b_by_a},
		current_time  = time.unix(CHAIN_NOW, 0),
	}
	c, err := x509.verify_chain(&leaf, opts); delete(c)
	testing.expect_value(t, err, x509.Error.Unknown_Authority)
}

// End-to-end: the self-signed RSA-SHA256 CA validates as a chain with itself
// as the trust anchor — the RSA PKCS#1 v1.5 signature check now runs.
@(test)
test_verify_chain_rsa_selfsigned :: proc(t: ^testing.T) {
	rsa, err := x509.parse(RSA_DER); defer x509.destroy(&rsa)
	testing.expect_value(t, err, x509.Error.None)
	opts := x509.Verify_Options{roots = {&rsa}, current_time = time.unix(CHAIN_NOW, 0)}
	c, verr := x509.verify_chain(&rsa, opts); defer delete(c)
	testing.expect_value(t, verr, x509.Error.None)
	testing.expect(t, len(c) >= 1, "RSA self-signed chain built")
}

// Each negative chain must be rejected for the right structural reason
// (all collapse to Unknown_Authority: no usable path to the anchor).
// Together these exercise the RFC 5280 6.1.4 issuer checks — keyCertSign,
// cA, intermediate validity, pathLenConstraint — which the happy-path
// tests never trip.
@(test)
test_verify_chain_bad_issuers :: proc(t: ^testing.T) {
	root, _ := x509.parse(NEG_ROOT); defer x509.destroy(&root)
	now := time.unix(CHAIN_NOW, 0)

	// Intermediate is a CA but its KeyUsage omits keyCertSign.
	{
		inter, _ := x509.parse(NEG_NOKCS_INTER); defer x509.destroy(&inter)
		leaf, _  := x509.parse(NEG_NOKCS_LEAF);  defer x509.destroy(&leaf)
		opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = now}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Unknown_Authority)
	}
	// Intermediate carries basicConstraints cA=FALSE.
	{
		inter, _ := x509.parse(NEG_NOTCA_INTER); defer x509.destroy(&inter)
		leaf, _  := x509.parse(NEG_NOTCA_LEAF);  defer x509.destroy(&leaf)
		opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = now}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Unknown_Authority)
	}
	// Intermediate is expired (validity 2010-2015): unlike the trust
	// anchor, an intermediate's validity IS enforced.
	{
		inter, _ := x509.parse(NEG_EXPINTER);      defer x509.destroy(&inter)
		leaf, _  := x509.parse(NEG_EXPINTER_LEAF); defer x509.destroy(&leaf)
		testing.expect_value(t, x509.valid_at(&inter, now), false)
		opts := x509.Verify_Options{roots = {&root}, intermediates = {&inter}, current_time = now}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Unknown_Authority)
	}
	// pathlen:0 on pl_a forbids pl_b (a CA) beneath it.
	{
		a, _    := x509.parse(NEG_PL_A);    defer x509.destroy(&a)
		b, _    := x509.parse(NEG_PL_B);    defer x509.destroy(&b)
		leaf, _ := x509.parse(NEG_PL_LEAF); defer x509.destroy(&leaf)
		opts := x509.Verify_Options{roots = {&root}, intermediates = {&a, &b}, current_time = now}
		c, err := x509.verify_chain(&leaf, opts); delete(c)
		testing.expect_value(t, err, x509.Error.Unknown_Authority)
	}
}

// Single-byte tamper sweep: no one-byte mutation of a signed certificate
// may BOTH parse cleanly AND verify against its true issuer. The whole
// TBSCertificate is signature-covered and the framing/algorithm/signature
// bytes are structurally checked, so every flip must be caught by parse
// or by the signature. A survivor would mean a trusted region the
// signature does not actually protect.
@(test)
test_verify_signature_tamper_sweep :: proc(t: ^testing.T) {
	check :: proc(t: ^testing.T, der, issuer_der: []byte) {
		issuer, ierr := x509.parse(issuer_der)
		defer x509.destroy(&issuer)
		testing.expect_value(t, ierr, x509.Error.None)

		buf := make([]byte, len(der))
		defer delete(buf)
		for pos in 0 ..< len(der) {
			copy(buf, der)
			buf[pos] ~= 0x01
			cert, perr := x509.parse(buf)
			if perr == .None {
				accepted := x509.verify_signature(&cert, &issuer) == .None
				x509.destroy(&cert)
				testing.expectf(t, !accepted, "tampered byte %d parsed and verified", pos)
			}
		}
	}
	check(t, EC_CHAIN_LEAF, EC_CHAIN_INTER)
	check(t, ED_CHAIN_LEAF, ED_CHAIN_ROOT)
}
