package main

// =============================================================================
// RISC-V DECODE-TABLE GENERATOR
// =============================================================================
//
// Two-level dispatch:
//
//   primary opcode (bits 6-0)         -> DECODE_INDEX_OPCODE  [128]
//     opcode 0x53 OP-FP -> by funct7  -> DECODE_INDEX_OP_FP   [128]
//
// 0x53 is the densest bucket (~40 entries: every F + D arithmetic /
// conversion / FMV / FCLASS / FEQ-FLT-FLE). Sub-bucketing by funct7
// brings the inner linear scan down to <= 3 candidates.
//
// All other primary opcodes have <= 22 entries; linear scan within the
// primary bucket is fine. Entries within a bucket are sorted by mask-
// popcount descending so the most-specific encoding form is matched first.
//
// Run with:  cd riscv && odin run tools/gen_decode_tables.odin -file
// Output:    ./decoding_tables.odin

import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"
import "core:math/bits"

import rv "../"

Entry :: struct {
	mnemonic:   rv.Mnemonic,
	ops:        [4]rv.Operand_Type,
	enc:        [4]rv.Operand_Encoding,
	bits:       u32,
	mask:       u32,
	feature: rv.Feature,
	flags:      rv.Encoding_Flags,
	primary_op: u8,
	sub_key:    u8,    // funct7 for opcode 0x53
	is_rvc:     bool,  // 2-byte compressed instruction
	rvc_key:    u8,    // RVC dispatch key: (op[1:0] | funct3[15:13]<<2), 5 bits
}

Range :: struct {
	start: u16,
	count: u16,
}

main :: proc() {
	fmt.println("Generating RISC-V decoder tables from ENCODING_TABLE...")

	all: [dynamic]Entry
	defer delete(all)

	for mn in rv.Mnemonic {
		for f in rv.ENCODING_TABLE[mn] {
			ilen := rv.inst_size_from_bits(f.bits)
			e := Entry{
				mnemonic = mn,
				ops      = f.ops,
				enc      = f.enc,
				bits     = f.bits,
				mask     = f.mask,
				feature  = f.feature,
				flags    = f.flags,
				is_rvc   = ilen == 2,
			}
			if e.is_rvc {
				// RVC: 5-bit dispatch (op[1:0] + funct3[15:13]<<2).
				e.rvc_key = u8((f.bits & 0x3) | ((f.bits >> 13) & 0x7) << 2)
			} else {
				e.primary_op = u8(f.bits & 0x7F)
				if e.primary_op == 0x53 {
					e.sub_key = u8((f.bits >> 25) & 0x7F)
				}
			}
			append(&all, e)
		}
	}

	slice.sort_by(all[:], proc(a, b: Entry) -> bool {
		if a.is_rvc != b.is_rvc { return !a.is_rvc }   // non-RVC first
		if a.is_rvc {
			if a.rvc_key != b.rvc_key { return a.rvc_key < b.rvc_key }
		} else {
			if a.primary_op != b.primary_op { return a.primary_op < b.primary_op }
			if a.sub_key    != b.sub_key    { return a.sub_key    < b.sub_key    }
		}
		ac := bits.count_ones(a.mask)
		bc := bits.count_ones(b.mask)
		if ac != bc { return ac > bc }
		return u16(a.mnemonic) < u16(b.mnemonic)
	})

	primary_idx: [128]Range
	op_fp_idx:   [128]Range
	rvc_idx:     [32]Range

	for e, i in all {
		if e.is_rvc {
			push_range(&rvc_idx[e.rvc_key], u16(i))
		} else {
			push_range(&primary_idx[e.primary_op], u16(i))
			if e.primary_op == 0x53 {
				push_range(&op_fp_idx[e.sub_key], u16(i))
			}
		}
	}

	sb: strings.Builder
	strings.builder_init(&sb)
	defer strings.builder_destroy(&sb)

	emit_header(&sb)
	emit_entries(&sb, all[:])
	emit_range_table(&sb, "DECODE_INDEX_OPCODE", primary_idx[:])
	emit_range_table(&sb, "DECODE_INDEX_OP_FP",  op_fp_idx[:])
	emit_range_table(&sb, "DECODE_INDEX_RVC",    rvc_idx[:])

	err := os.write_entire_file("decoding_tables.odin", transmute([]u8)strings.to_string(sb))
	if err != nil {
		fmt.eprintfln("FAILED to write decoding_tables.odin: %v", err)
		os.exit(1)
	}

	max_primary, max_opfp, max_rvc: u16
	populated_primary, populated_rvc: int
	for r in primary_idx {
		if r.count > max_primary  { max_primary  = r.count }
		if r.count > 0            { populated_primary += 1 }
	}
	for r in op_fp_idx {
		if r.count > max_opfp { max_opfp = r.count }
	}
	for r in rvc_idx {
		if r.count > max_rvc { max_rvc = r.count }
		if r.count > 0       { populated_rvc += 1 }
	}
	fmt.printfln("OK -- %d entries; primary=%d buckets (max=%d); OP-FP max=%d; RVC=%d buckets (max=%d)",
				 len(all), populated_primary, max_primary, max_opfp, populated_rvc, max_rvc)
}

push_range :: proc(r: ^Range, i: u16) {
	if r.count == 0 { r.start = i }
	r.count += 1
}

emit_header :: proc(sb: ^strings.Builder) {
	strings.write_string(sb, `package rexcode_riscv

// =============================================================================
// GENERATED FILE - DO NOT EDIT
// =============================================================================
//
// Generated by tools/gen_decode_tables.odin from ENCODING_TABLE.
// Regenerate with:  cd riscv && odin run tools/gen_decode_tables.odin -file
//

Decode_Entry :: struct #packed {
	mnemonic: Mnemonic,
	ops:      [4]Operand_Type,
	enc:      [4]Operand_Encoding,
	bits:     u32,
	mask:     u32,
	feature: Feature,
	flags:    Encoding_Flags,
}
#assert(size_of(Decode_Entry) == 20)

Decode_Index :: struct #packed {
	start: u16,
	count: u16,
}
#assert(size_of(Decode_Index) == 4)

`)
}

emit_entries :: proc(sb: ^strings.Builder, entries: []Entry) {
	fmt.sbprintfln(sb, "@(rodata)")
	fmt.sbprintfln(sb, "DECODE_ENTRIES := [%d]Decode_Entry{{", len(entries))
	for e in entries {
		flags_str := encode_flags_literal(e.flags)
		fmt.sbprintfln(sb,
			"\t{{.%v, {{.%v, .%v, .%v, .%v}}, {{.%v, .%v, .%v, .%v}}, 0x%08X, 0x%08X, .%v, {{%s}}}},",
			e.mnemonic,
			e.ops[0], e.ops[1], e.ops[2], e.ops[3],
			e.enc[0], e.enc[1], e.enc[2], e.enc[3],
			e.bits, e.mask, e.feature, flags_str)
	}
	strings.write_string(sb, "}\n\n")
}

encode_flags_literal :: proc(f: rv.Encoding_Flags) -> string {
	sb: strings.Builder
	strings.builder_init(&sb)
	first := true
	write := proc(sb: ^strings.Builder, first: ^bool, s: string) {
		if !first^ { strings.write_string(sb, ", ") }
		strings.write_string(sb, s)
		first^ = false
	}
	if f.rv32_only { write(&sb, &first, "rv32_only=true") }
	if f.rv64_only { write(&sb, &first, "rv64_only=true") }
	if f.branch    { write(&sb, &first, "branch=true")    }
	if f.fp_round  { write(&sb, &first, "fp_round=true")  }
	return strings.to_string(sb)
}

emit_range_table :: proc(sb: ^strings.Builder, name: string, ranges: []Range) {
	fmt.sbprintfln(sb, "@(rodata)")
	fmt.sbprintfln(sb, "%s := [%d]Decode_Index{{", name, len(ranges))
	for r, i in ranges {
		if r.count != 0 {
			fmt.sbprintfln(sb, "\t0x%02X = {{%d, %d}},", i, r.start, r.count)
		}
	}
	strings.write_string(sb, "}\n\n")
}
