package rexcode_ppc_vle

// =============================================================================
// PowerPC VLE Encoding Table
// =============================================================================
//
// 222 entries auto-generated from binutils PPCVLE set with form-aware operand
// encoding. Each entry's mask covers the FIXED bits of the form (primary
// opcode, sub-opcode, baked operands), leaving variable operand bits free.
@(rodata)
ENCODING_TABLE: [Mnemonic][]Encoding = #partial {
	.SE_ILLEGAL           = { {.SE_ILLEGAL          , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000000, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_ISYNC             = { {.SE_ISYNC            , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000001, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SC                = { {.SE_SC               , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000002, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BLR               = { {.SE_BLR              , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000004, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BLRL              = { {.SE_BLRL             , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000005, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true, writes_lr=true}} },
	.SE_BCTR              = { {.SE_BCTR             , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000006, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BCTRL             = { {.SE_BCTRL            , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000007, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true, writes_lr=true}} },
	.SE_RFI               = { {.SE_RFI              , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000008, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_RFCI              = { {.SE_RFCI             , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x00000009, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_RFDI              = { {.SE_RFDI             , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x0000000A, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_RFMCI             = { {.SE_RFMCI            , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x0000000B, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_RFGI              = { {.SE_RFGI             , {.NONE, .NONE, .NONE, .NONE}, {.NONE, .NONE, .NONE, .NONE}, 0x0000000C, 0xFFFFFFFF, .BASE, .PPC32_VLE, {short=true}} },
	.SE_NOT               = { {.SE_NOT              , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x00000020, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_NEG               = { {.SE_NEG              , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x00000030, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_MFLR              = { {.SE_MFLR             , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x00000080, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_MTLR              = { {.SE_MTLR             , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x00000090, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_MFCTR             = { {.SE_MFCTR            , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x000000A0, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_MTCTR             = { {.SE_MTCTR            , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x000000B0, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_EXTZB             = { {.SE_EXTZB            , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x000000C0, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_EXTSB             = { {.SE_EXTSB            , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x000000D0, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_EXTZH             = { {.SE_EXTZH            , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x000000E0, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_EXTSH             = { {.SE_EXTSH            , {.GPR_VLE16, .NONE, .NONE, .NONE}, {.RX, .NONE, .NONE, .NONE}, 0x000000F0, 0xFFFFFFF0, .BASE, .PPC32_VLE, {short=true}} },
	.SE_MR                = { {.SE_MR               , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000100, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_MTAR              = { {.SE_MTAR             , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000200, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_MFAR              = { {.SE_MFAR             , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000300, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_ADD               = { {.SE_ADD              , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000400, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_MULLW             = { {.SE_MULLW            , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000500, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SUB               = { {.SE_SUB              , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000600, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SUBF              = { {.SE_SUBF             , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000700, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_CMP               = { {.SE_CMP              , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000C00, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_CMPL              = { {.SE_CMPL             , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000D00, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_CMPH              = { {.SE_CMPH             , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000E00, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_CMPHL             = { {.SE_CMPHL            , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00000F00, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.E_CMPI               = { {.E_CMPI              , {.CR_FIELD, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800A800, 0xFC60F800, .BASE, .PPC32_VLE, {}} },
	.E_CMPWI              = { {.E_CMPWI             , {.CR_FIELD, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800A800, 0xFC60F800, .BASE, .PPC32_VLE, {}} },
	.E_CMPLI              = { {.E_CMPLI             , {.CR_FIELD, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1808A800, 0xFC60F800, .BASE, .PPC32_VLE, {}} },
	.E_CMPLWI             = { {.E_CMPLWI            , {.CR_FIELD, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1808A800, 0xFC60F800, .BASE, .PPC32_VLE, {}} },
	.E_ADDI               = { {.E_ADDI              , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x18008000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_SUBI               = { {.E_SUBI              , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x18008000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_ADDI_DOT           = { {.E_ADDI_DOT          , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x18008800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_ADDIC              = { {.E_ADDIC             , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x18009000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_SUBIC              = { {.E_SUBIC             , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x18009000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_ADDIC_DOT          = { {.E_ADDIC_DOT         , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x18009800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_SUBIC_DOT          = { {.E_SUBIC_DOT         , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x18009800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_MULLI              = { {.E_MULLI             , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800A000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_SUBFIC             = { {.E_SUBFIC            , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800B000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_SUBFIC_DOT         = { {.E_SUBFIC_DOT        , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800B800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_ANDI               = { {.E_ANDI              , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800C000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_ANDI_DOT           = { {.E_ANDI_DOT          , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800C800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_NOP                = { {.E_NOP               , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800D000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_ORI                = { {.E_ORI               , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800D000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_ORI_DOT            = { {.E_ORI_DOT           , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800D800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_XORI               = { {.E_XORI              , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800E000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_XORI_DOT           = { {.E_XORI_DOT          , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SCI8, .NONE}, 0x1800E800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_LBZU               = { {.E_LBZU              , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LHAU               = { {.E_LHAU              , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000300, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LHZU               = { {.E_LHZU              , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000100, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LMW                = { {.E_LMW               , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000800, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LWZU               = { {.E_LWZU              , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000200, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STBU               = { {.E_STBU              , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000400, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STHU               = { {.E_STHU              , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000500, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STWU               = { {.E_STWU              , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000600, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STMW               = { {.E_STMW              , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18000900, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LMVGPRW            = { {.E_LMVGPRW           , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18001000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LDMVGPRW           = { {.E_LDMVGPRW          , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18001000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STMVGPRW           = { {.E_STMVGPRW          , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18001100, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LMVSPRW            = { {.E_LMVSPRW           , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18201000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LDMVSPRW           = { {.E_LDMVSPRW          , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18201000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STMVSPRW           = { {.E_STMVSPRW          , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18201100, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LMVSRRW            = { {.E_LMVSRRW           , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18801000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LDMVSRRW           = { {.E_LDMVSRRW          , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18801000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STMVSRRW           = { {.E_STMVSRRW          , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18801100, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LMVCSRRW           = { {.E_LMVCSRRW          , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18A01000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LDMVCSRRW          = { {.E_LDMVCSRRW         , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18A01000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STMVCSRRW          = { {.E_STMVCSRRW         , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18A01100, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LMVDSRRW           = { {.E_LMVDSRRW          , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18C01000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LDMVDSRRW          = { {.E_LDMVDSRRW         , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18C01000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STMVDSRRW          = { {.E_STMVDSRRW         , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18C01100, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_LMVMCSRRW          = { {.E_LMVMCSRRW         , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18E01000, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_STMVMCSRRW         = { {.E_STMVMCSRRW        , {.GPR, .GPR, .NONE, .NONE}, {.RT, .RA, .NONE, .NONE}, 0x18E01100, 0xFC00FFFF, .BASE, .PPC32_VLE, {}} },
	.E_ADD16I             = { {.E_ADD16I            , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x1C000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.E_LA                 = { {.E_LA                , {.GPR, .MEM, .NONE, .NONE}, {.RT, .OFFSET_BASE_D, .NONE, .NONE}, 0x1C000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.E_SUB16I             = { {.E_SUB16I            , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x1C000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.SE_ADDI              = { {.SE_ADDI             , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00002000, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_CMPLI             = { {.SE_CMPLI            , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00002200, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SUBI              = { {.SE_SUBI             , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00002400, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SUBI_DOT          = { {.SE_SUBI_DOT         , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00002600, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true, sets_cr0=true}} },
	.SE_CMPI              = { {.SE_CMPI             , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00002A00, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BMASKI            = { {.SE_BMASKI           , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00002C00, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_ANDI              = { {.SE_ANDI             , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00002E00, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.E_LBZ                = { {.E_LBZ               , {.GPR, .MEM, .NONE, .NONE}, {.RT, .OFFSET_BASE_D, .NONE, .NONE}, 0x30000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.E_STB                = { {.E_STB               , {.GPR, .MEM, .NONE, .NONE}, {.RT, .OFFSET_BASE_D, .NONE, .NONE}, 0x34000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.E_LHA                = { {.E_LHA               , {.GPR, .MEM, .NONE, .NONE}, {.RT, .OFFSET_BASE_D, .NONE, .NONE}, 0x38000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.SE_SRW               = { {.SE_SRW              , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00004000, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SRAW              = { {.SE_SRAW             , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00004100, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SLW               = { {.SE_SLW              , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00004200, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_NOP               = { {.SE_NOP              , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00004400, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_OR                = { {.SE_OR               , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00004400, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_ANDC              = { {.SE_ANDC             , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00004500, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_AND               = { {.SE_AND              , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00004600, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_AND_DOT           = { {.SE_AND_DOT          , {.GPR_VLE16, .GPR_VLE16, .NONE, .NONE}, {.RX, .RY, .NONE, .NONE}, 0x00004700, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, sets_cr0=true}} },
	.SE_LI                = { {.SE_LI               , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RY, .UI7, .NONE, .NONE}, 0x00004800, 0xFFFFF800, .BASE, .PPC32_VLE, {short=true}} },
	.E_LWZ                = { {.E_LWZ               , {.GPR, .MEM, .NONE, .NONE}, {.RT, .OFFSET_BASE_D, .NONE, .NONE}, 0x50000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.E_STW                = { {.E_STW               , {.GPR, .MEM, .NONE, .NONE}, {.RT, .OFFSET_BASE_D, .NONE, .NONE}, 0x54000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.E_LHZ                = { {.E_LHZ               , {.GPR, .MEM, .NONE, .NONE}, {.RT, .OFFSET_BASE_D, .NONE, .NONE}, 0x58000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.E_STH                = { {.E_STH               , {.GPR, .MEM, .NONE, .NONE}, {.RT, .OFFSET_BASE_D, .NONE, .NONE}, 0x5C000000, 0xFC000000, .BASE, .PPC32_VLE, {}} },
	.SE_BCLRI             = { {.SE_BCLRI            , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00006000, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BGENI             = { {.SE_BGENI            , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00006200, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BSETI             = { {.SE_BSETI            , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00006400, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BTSTI             = { {.SE_BTSTI            , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00006600, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SRWI              = { {.SE_SRWI             , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00006800, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SRAWI             = { {.SE_SRAWI            , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00006A00, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_SLWI              = { {.SE_SLWI             , {.GPR_VLE16, .IMM, .NONE, .NONE}, {.RX, .UI5, .NONE, .NONE}, 0x00006C00, 0xFFFFFE00, .BASE, .PPC32_VLE, {short=true}} },
	.E_LIS                = { {.E_LIS               , {.GPR, .IMM, .NONE, .NONE}, {.RT, .UI16, .NONE, .NONE}, 0x7000E000, 0xFC1FF800, .BASE, .PPC32_VLE, {}} },
	.E_AND2IS_DOT         = { {.E_AND2IS_DOT        , {.GPR, .IMM, .NONE, .NONE}, {.RT, .UI16, .NONE, .NONE}, 0x7000E800, 0xFC1FF800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_OR2IS              = { {.E_OR2IS             , {.GPR, .IMM, .NONE, .NONE}, {.RT, .UI16, .NONE, .NONE}, 0x7000D000, 0xFC1FF800, .BASE, .PPC32_VLE, {}} },
	.E_AND2I_DOT          = { {.E_AND2I_DOT         , {.GPR, .IMM, .NONE, .NONE}, {.RT, .UI16, .NONE, .NONE}, 0x7000C800, 0xFC1FF800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_OR2I               = { {.E_OR2I              , {.GPR, .IMM, .NONE, .NONE}, {.RT, .UI16, .NONE, .NONE}, 0x7000C000, 0xFC1FF800, .BASE, .PPC32_VLE, {}} },
	.E_CMPHL16I           = { {.E_CMPHL16I          , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x7000B800, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_CMPH16I            = { {.E_CMPH16I           , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x7000B000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_CMPL16I            = { {.E_CMPL16I           , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x7000A800, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_MULL2I             = { {.E_MULL2I            , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x7000A000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_CMP16I             = { {.E_CMP16I            , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x70009800, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_SUB2IS             = { {.E_SUB2IS            , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x70009000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_ADD2IS             = { {.E_ADD2IS            , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x70009000, 0xFC00F800, .BASE, .PPC32_VLE, {}} },
	.E_SUB2I_DOT          = { {.E_SUB2I_DOT         , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x70008800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_ADD2I_DOT          = { {.E_ADD2I_DOT         , {.GPR, .GPR, .IMM, .NONE}, {.RT, .RA, .SI16, .NONE}, 0x70008800, 0xFC00F800, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_LI                 = { {.E_LI                , {.GPR, .IMM, .NONE, .NONE}, {.RT, .LI20, .NONE, .NONE}, 0x70000000, 0xFC008000, .BASE, .PPC32_VLE, {}} },
	.E_RLWIMI             = { {.E_RLWIMI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x74000000, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_INSLWI             = { {.E_INSLWI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x74000000, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_INSRWI             = { {.E_INSRWI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x74000000, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_ROTLWI             = { {.E_ROTLWI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7400003F, 0xFC00003F, .BASE, .PPC32_VLE, {}} },
	.E_ROTRWI             = { {.E_ROTRWI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7400003F, 0xFC00003F, .BASE, .PPC32_VLE, {}} },
	.E_CLRLWI             = { {.E_CLRLWI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7400003F, 0xFC00003F, .BASE, .PPC32_VLE, {}} },
	.E_CLRRWI             = { {.E_CLRRWI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x74000001, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_RLWINM             = { {.E_RLWINM            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x74000001, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_EXTLWI             = { {.E_EXTLWI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x74000001, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_EXTRWI             = { {.E_EXTRWI            , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7400003F, 0xFC00003F, .BASE, .PPC32_VLE, {}} },
	.E_CLRLSLWI           = { {.E_CLRLSLWI          , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x74000001, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_B                  = { {.E_B                 , {.REL, .NONE, .NONE, .NONE}, {.B24, .NONE, .NONE, .NONE}, 0x78000000, 0xFC000001, .BASE, .PPC32_VLE, {}} },
	.E_BL                 = { {.E_BL                , {.REL, .NONE, .NONE, .NONE}, {.B24, .NONE, .NONE, .NONE}, 0x78000001, 0xFC000001, .BASE, .PPC32_VLE, {}} },
	.E_BDNZ               = { {.E_BDNZ              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A200000, 0xFFF00001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BDNZL              = { {.E_BDNZL             , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A200001, 0xFFF00001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BDZ                = { {.E_BDZ               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A300000, 0xFFF00001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BDZL               = { {.E_BDZL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A300001, 0xFFF00001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BGE                = { {.E_BGE               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A000000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BGEL               = { {.E_BGEL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A000001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BNL                = { {.E_BNL               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A000000, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BNLL               = { {.E_BNLL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A000001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BLT                = { {.E_BLT               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A100000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BLTL               = { {.E_BLTL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A100001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BGT                = { {.E_BGT               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A110000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BGTL               = { {.E_BGTL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A110001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BLE                = { {.E_BLE               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A010000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BLEL               = { {.E_BLEL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A010001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BNG                = { {.E_BNG               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A010000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BNGL               = { {.E_BNGL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A010001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BNE                = { {.E_BNE               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A020000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BNEL               = { {.E_BNEL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A020001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BEQ                = { {.E_BEQ               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A120000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BEQL               = { {.E_BEQL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A120001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BSO                = { {.E_BSO               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A130000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BSOL               = { {.E_BSOL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A130001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BUN                = { {.E_BUN               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A130000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BUNL               = { {.E_BUNL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A130001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BNS                = { {.E_BNS               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A030000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BNSL               = { {.E_BNSL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A030001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BNU                = { {.E_BNU               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A030000, 0xFFFF0001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BNUL               = { {.E_BNUL              , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A030001, 0xFFFF0001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BC                 = { {.E_BC                , {.BO, .CR_BIT, .REL, .NONE}, {.BO32, .BI32, .B15, .NONE}, 0x7A000000, 0xFFC00001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BCL                = { {.E_BCL               , {.BO, .CR_BIT, .REL, .NONE}, {.BO32, .BI32, .B15, .NONE}, 0x7A000001, 0xFFC00001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BF                 = { {.E_BF                , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A000000, 0xFFF00001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BFL                = { {.E_BFL               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A000001, 0xFFF00001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_BT                 = { {.E_BT                , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A100000, 0xFFF00001, .BASE, .PPC32_VLE, {cond_branch=true}} },
	.E_BTL                = { {.E_BTL               , {.REL, .NONE, .NONE, .NONE}, {.B15, .NONE, .NONE, .NONE}, 0x7A100001, 0xFFF00001, .BASE, .PPC32_VLE, {writes_lr=true, cond_branch=true}} },
	.E_CMPH               = { {.E_CMPH              , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C00001C, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_SC                 = { {.E_SC                , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000048, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CMPHL              = { {.E_CMPHL             , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C00005C, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CRANDC             = { {.E_CRANDC            , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000102, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CRNAND             = { {.E_CRNAND            , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C0001C2, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CRNOT              = { {.E_CRNOT             , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000042, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CRNOR              = { {.E_CRNOR             , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000042, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CRCLR              = { {.E_CRCLR             , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000182, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CRXOR              = { {.E_CRXOR             , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000182, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_MCRF               = { {.E_MCRF              , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000020, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_SLWI               = { {.E_SLWI              , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000070, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_SLWI_DOT           = { {.E_SLWI_DOT          , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000071, 0xFC0007FF, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_CRAND              = { {.E_CRAND             , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000202, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_RLW                = { {.E_RLW               , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000230, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_RLW_DOT            = { {.E_RLW_DOT           , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000231, 0xFC0007FF, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_CRSET              = { {.E_CRSET             , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000242, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CREQV              = { {.E_CREQV             , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000242, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_RLWI               = { {.E_RLWI              , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000270, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_RLWI_DOT           = { {.E_RLWI_DOT          , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000271, 0xFC0007FF, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.E_CRORC              = { {.E_CRORC             , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000342, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CRMOVE             = { {.E_CRMOVE            , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000382, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_CROR               = { {.E_CROR              , {.BO, .CR_BIT, .NONE, .NONE}, {.BO32, .BI32, .NONE, .NONE}, 0x7C000382, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_SRWI               = { {.E_SRWI              , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000470, 0xFC0007FF, .BASE, .PPC32_VLE, {}} },
	.E_SRWI_DOT           = { {.E_SRWI_DOT          , {.GPR, .GPR, .GPR, .NONE}, {.RT, .RA, .RB, .NONE}, 0x7C000471, 0xFC0007FF, .BASE, .PPC32_VLE, {sets_cr0=true}} },
	.SE_LBZ               = { {.SE_LBZ              , {.GPR_VLE16, .MEM, .NONE, .NONE}, {.RZ, .OFFSET_BASE_SD4, .NONE, .NONE}, 0x00008000, 0xFFFFF000, .BASE, .PPC32_VLE, {short=true}} },
	.SE_STB               = { {.SE_STB              , {.GPR_VLE16, .MEM, .NONE, .NONE}, {.RZ, .OFFSET_BASE_SD4, .NONE, .NONE}, 0x00009000, 0xFFFFF000, .BASE, .PPC32_VLE, {short=true}} },
	.SE_LHZ               = { {.SE_LHZ              , {.GPR_VLE16, .MEM, .NONE, .NONE}, {.RZ, .OFFSET_BASE_SD4_H, .NONE, .NONE}, 0x0000A000, 0xFFFFF000, .BASE, .PPC32_VLE, {short=true}} },
	.SE_STH               = { {.SE_STH              , {.GPR_VLE16, .MEM, .NONE, .NONE}, {.RZ, .OFFSET_BASE_SD4_H, .NONE, .NONE}, 0x0000B000, 0xFFFFF000, .BASE, .PPC32_VLE, {short=true}} },
	.SE_LWZ               = { {.SE_LWZ              , {.GPR_VLE16, .MEM, .NONE, .NONE}, {.RZ, .OFFSET_BASE_SD4_W, .NONE, .NONE}, 0x0000C000, 0xFFFFF000, .BASE, .PPC32_VLE, {short=true}} },
	.SE_STW               = { {.SE_STW              , {.GPR_VLE16, .MEM, .NONE, .NONE}, {.RZ, .OFFSET_BASE_SD4_W, .NONE, .NONE}, 0x0000D000, 0xFFFFF000, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BGE               = { {.SE_BGE              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E000, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BNL               = { {.SE_BNL              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E000, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BLE               = { {.SE_BLE              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E100, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BNG               = { {.SE_BNG              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E100, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BNE               = { {.SE_BNE              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E200, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BNS               = { {.SE_BNS              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E300, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BNU               = { {.SE_BNU              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E300, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BF                = { {.SE_BF               , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E000, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BLT               = { {.SE_BLT              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E400, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BGT               = { {.SE_BGT              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E500, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BEQ               = { {.SE_BEQ              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E600, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BSO               = { {.SE_BSO              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E700, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BUN               = { {.SE_BUN              , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E700, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BT                = { {.SE_BT               , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E400, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_BC                = { {.SE_BC               , {.BO, .CR_BIT, .REL, .NONE}, {.BO16, .BI16, .B8, .NONE}, 0x0000E000, 0xFFFFF800, .BASE, .PPC32_VLE, {short=true, cond_branch=true}} },
	.SE_B                 = { {.SE_B                , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E800, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
	.SE_BL                = { {.SE_BL               , {.REL, .NONE, .NONE, .NONE}, {.B8, .NONE, .NONE, .NONE}, 0x0000E900, 0xFFFFFF00, .BASE, .PPC32_VLE, {short=true}} },
}
