package all

// Imports every package
// This is useful for knowing what exists and producing documentation with `odin doc`

import "core:bufio"
import "core:bytes"
import "core:c"
import c_tokenizer "core:c/frontend/tokenizer"
import c_preprocessor "core:c/frontend/preprocessor"
import "core:compress"
import "core:compress/gzip"
import "core:compress/zlib"
import "core:container"
import "core:dynlib"
import "core:encoding"
import "core:encoding/base32"
import "core:encoding/base64"
import "core:encoding/csv"
import "core:encoding/hxa"
import "core:encoding/json"
import "core:fmt"
import "core:hash"
import "core:image"
import "core:image/png"
import "core:io"
import "core:log"
import "core:math"
import "core:math/big"
import "core:math/bits"
import "core:math/fixed"
import "core:math/linalg"
import "core:math/rand"
import "core:mem"
import "core:odin/ast"
import doc_format "core:odin/doc-format"
import "core:odin/format"
import "core:odin/parser"
import "core:odin/printer"
import odin_tokenizer "core:odin/tokenizer"
import "core:os"
import "core:path"
import "core:path/filepath"
import "core:reflect"
import "core:runtime"
import "core:slice"
import "core:sort"
import "core:strconv"
import "core:strings"
import "core:sync"
import "core:sync/sync2"
import "core:text/scanner"
import "core:thread"
import "core:time"
import "core:unicode"
import "core:unicode/utf8"
import "core:unicode/utf16"

main :: proc(){}
