package main

// =============================================================================
// PowerPC VLE Decode-Table Generator
// =============================================================================
//
// VLE has two dispatch namespaces:
//   - 16-bit (flags.short=true) — primary key = bits 10..15 of halfword (6 bits)
//   - 32-bit                    — primary key = bits 26..31 of word (6 bits)
//
// Both fit in 64-bucket primary tables. Within a bucket, entries are sorted
// by mask popcount descending so the most-specific form matches first.

import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"
import "core:math/bits"

import v ".."

Range :: struct #packed {
	start: u32,
	count: u16,
	_:  u16,
}

Entry :: struct {
	mn:       v.Mnemonic,
	ops:      [4]v.Operand_Type,
	enc:      [4]v.Operand_Encoding,
	bits:     u32,
	mask:     u32,
	feature:  v.Feature,
	mode:     v.Mode,
	flags:    v.Encoding_Flags,
	form_idx: u16,
}

PRIMARY_BUCKETS :: 64

Pair :: struct { bucket: u16, entry_idx: u16 }

main :: proc() {
	fmt.println("Generating PowerPC VLE decoder tables...")

	all: [dynamic]Entry
	defer delete(all)

	for mn in v.Mnemonic {
		for f, fi in v.ENCODING_TABLE[mn] {
			append(&all, Entry{
				mn = mn, ops = f.ops, enc = f.enc,
				bits = f.bits, mask = f.mask,
				feature = f.feature, mode = f.mode, flags = f.flags,
				form_idx = u16(fi),
			})
		}
	}

	slice.sort_by(all[:], proc(x, y: Entry) -> bool {
		px := primary_key(x)
		py := primary_key(y)
		if px != py { return px < py }
		if x.flags.short != y.flags.short { return x.flags.short }
		xc := bits.count_ones(x.mask)
		yc := bits.count_ones(y.mask)
		if xc != yc { return xc > yc }
		return u16(x.mn) < u16(y.mn)
	})

	short_pairs: [dynamic]Pair
	long_pairs:  [dynamic]Pair
	defer delete(short_pairs); defer delete(long_pairs)

	for e, i in all {
		key := primary_key(e)
		p := Pair{bucket = key, entry_idx = u16(i)}
		if e.flags.short {
			append(&short_pairs, p)
		} else {
			append(&long_pairs, p)
		}
	}

	rebuild :: proc(pairs: ^[dynamic]Pair, all: []Entry) {
		Sort_Pair :: struct { sort_key: u64, entry_idx: u16, bucket: u16 }
		sortable := make([dynamic]Sort_Pair, 0, len(pairs), context.temp_allocator)
		for p in pairs^ {
			e := all[p.entry_idx]
			pop := u64(bits.count_ones(e.mask))
			key := (u64(p.bucket) << 40) | ((63 - pop) << 32) | u64(e.mn)
			append(&sortable, Sort_Pair{sort_key = key, entry_idx = p.entry_idx, bucket = p.bucket})
		}
		slice.sort_by_key(sortable[:], proc(s: Sort_Pair) -> u64 { return s.sort_key })
		clear(pairs)
		for s in sortable { append(pairs, Pair{bucket = s.bucket, entry_idx = s.entry_idx}) }
	}
	rebuild(&short_pairs, all[:])
	rebuild(&long_pairs,  all[:])

	short_idx: [PRIMARY_BUCKETS]Range
	long_idx:  [PRIMARY_BUCKETS]Range
	bucket_list: [dynamic]u16
	defer delete(bucket_list)

	emit_pairs :: proc(pairs: []Pair, idx: []Range, list: ^[dynamic]u16) {
		prev: i32 = -1
		for p in pairs {
			cur := i32(p.bucket)
			if cur != prev {
				idx[cur].start = u32(len(list))
				idx[cur].count = 0
				prev = cur
			}
			append(list, p.entry_idx)
			idx[cur].count += 1
		}
	}
	emit_pairs(short_pairs[:], short_idx[:], &bucket_list)
	emit_pairs(long_pairs[:],  long_idx[:],  &bucket_list)

	sb: strings.Builder
	strings.builder_init(&sb)
	defer strings.builder_destroy(&sb)

	strings.write_string(&sb, `package rexcode_ppc_vle

// =============================================================================
// GENERATED FILE — DO NOT EDIT
// =============================================================================
//
// Generated by tools/gen_decode_tables.odin from ENCODING_TABLE.
// Regenerate with:  cd ppc_vle && odin run tools/gen_decode_tables.odin -file

Decode_Entry :: struct #packed {
	mnemonic: Mnemonic,
	ops:      [4]Operand_Type,
	enc:      [4]Operand_Encoding,
	bits:     u32,
	mask:     u32,
	feature:  Feature,
	mode:     Mode,
	flags:    Encoding_Flags,
}

Decode_Index :: struct #packed {
	start: u32,
	count: u16,
	_:     u16,
}

`)

	fmt.sbprintfln(&sb, "@(rodata)")
	fmt.sbprintfln(&sb, "DECODE_ENTRIES := [%d]Decode_Entry{{", len(all))
	for e in all {
		flags_str := flags_literal(e.flags)
		fmt.sbprintfln(&sb,
			"\t{{ .%v, {{.%v, .%v, .%v, .%v}}, {{.%v, .%v, .%v, .%v}}, 0x%08X, 0x%08X, .%v, .%v, {{%s}} }},",
			e.mn,
			e.ops[0], e.ops[1], e.ops[2], e.ops[3],
			e.enc[0], e.enc[1], e.enc[2], e.enc[3],
			e.bits, e.mask, e.feature, e.mode, flags_str)
	}
	strings.write_string(&sb, "}\n\n")

	fmt.sbprintf(&sb, "DECODE_FORM_IDX := [%d]u16{{\n", len(all))
	for e, i in all {
		if i > 0 && i % 16 == 0 { strings.write_string(&sb, "\n") }
		fmt.sbprintf(&sb, " %d,", e.form_idx)
	}
	strings.write_string(&sb, "\n}\n\n")

	fmt.sbprintf(&sb, "DECODE_BUCKET_LIST := [%d]u16{{\n", len(bucket_list))
	for v, i in bucket_list {
		if i > 0 && i % 16 == 0 { strings.write_string(&sb, "\n") }
		fmt.sbprintf(&sb, " %d,", v)
	}
	strings.write_string(&sb, "\n}\n\n")

	emit_range_table(&sb, "DECODE_INDEX_SHORT", short_idx[:])
	emit_range_table(&sb, "DECODE_INDEX_LONG",  long_idx[:])

	err := os.write_entire_file("decoding_tables.odin", transmute([]u8)strings.to_string(sb))
	if err != nil {
		fmt.eprintfln("FAILED: %v", err); os.exit(1)
	}

	max_s, max_l: u16
	pop_s, pop_l: int
	for r in short_idx { if r.count > max_s { max_s = r.count }; if r.count > 0 { pop_s += 1 } }
	for r in long_idx  { if r.count > max_l { max_l = r.count }; if r.count > 0 { pop_l += 1 } }
	fmt.printfln("OK — %d entries: SHORT %d/64 buckets (max=%d); LONG %d/64 buckets (max=%d); bucket_list %d",
				 len(all), pop_s, max_s, pop_l, max_l, len(bucket_list))
}

primary_key :: proc(e: Entry) -> u16 {
	if e.flags.short {
		return u16((e.bits >> 10) & 0x3F)
	}
	return u16((e.bits >> 26) & 0x3F)
}

flags_literal :: proc(f: v.Encoding_Flags) -> string {
	sb: strings.Builder
	strings.builder_init(&sb)
	first := true
	w :: proc(sb: ^strings.Builder, first: ^bool, s: string) {
		if !first^ { strings.write_string(sb, ", ") }
		strings.write_string(sb, s)
		first^ = false
	}
	if f.short       { w(&sb, &first, "short=true")       }
	if f.cond_branch { w(&sb, &first, "cond_branch=true") }
	if f.writes_lr   { w(&sb, &first, "writes_lr=true")   }
	if f.sets_cr0    { w(&sb, &first, "sets_cr0=true")    }
	return strings.to_string(sb)
}

emit_range_table :: proc(sb: ^strings.Builder, name: string, ranges: []Range) {
	fmt.sbprintfln(sb, "@(rodata)")
	fmt.sbprintfln(sb, "%s := [%d]Decode_Index{{", name, len(ranges))
	for r, i in ranges {
		if r.count == 0 {
			if i % 16 == 0 { strings.write_string(sb, "\n") }
			strings.write_string(sb, "{0,0,0},")
		} else {
			fmt.sbprintf(sb, "{{%d,%d,0}},", r.start, r.count)
		}
	}
	strings.write_string(sb, "\n}\n\n")
}
