package main

// =============================================================================
// W65C816S DECODE-TABLE GENERATOR
// =============================================================================
//
// Same shape as mos6502/tools/gen_decode_tables.odin. Single-level
// dispatch (opcode byte directly indexes a 256-slot table).  Most
// opcodes have one entry; the mode-dependent immediates (LDA #imm,
// ADC #imm, etc.) have two entries sharing the same opcode, sorted so
// the 8-bit form is at lower index than the 16-bit form. The decoder
// picks based on Assumed_State.

import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"

import m "../"

Entry :: struct {
	mnemonic: m.Mnemonic,
	ops:      [4]m.Operand_Type,
	enc:      [4]m.Operand_Encoding,
	opcode:   u8,
	length:   u8,
	flags:    m.Encoding_Flags,
}

Range :: struct {
	start: u16,
	count: u16,
}

main :: proc() {
	fmt.println("Generating W65C816S decoder tables from ENCODING_TABLE...")

	all: [dynamic]Entry
	defer delete(all)

	for mn in m.Mnemonic {
		for f in m.ENCODING_TABLE[mn] {
			append(&all, Entry{
				mnemonic = mn, ops = f.ops, enc = f.enc,
				opcode = f.opcode, length = f.length, flags = f.flags,
			})
		}
	}

	// Sort: opcode asc; within an opcode, place IMM_X8/IMM_M8 (length 2)
	// before IMM_X16/IMM_M16 (length 3) by ascending length, then mnemonic
	// for stability.
	slice.sort_by(all[:], proc(a, b: Entry) -> bool {
		if a.opcode != b.opcode { return a.opcode < b.opcode }
		if a.length != b.length { return a.length < b.length }
		return u16(a.mnemonic) < u16(b.mnemonic)
	})

	opcode_idx: [256]Range
	for e, i in all {
		if opcode_idx[e.opcode].count == 0 {
			opcode_idx[e.opcode].start = u16(i)
		}
		opcode_idx[e.opcode].count += 1
	}

	sb: strings.Builder
	strings.builder_init(&sb)
	defer strings.builder_destroy(&sb)

	emit_header(&sb)
	emit_entries(&sb, all[:])
	emit_range_table(&sb, "DECODE_INDEX_OPCODE", opcode_idx[:])

	err := os.write_entire_file("decoding_tables.odin", transmute([]u8)strings.to_string(sb))
	if err != nil {
		fmt.eprintfln("FAILED to write decoding_tables.odin: %v", err)
		os.exit(1)
	}

	max_bucket: u16
	populated:  int
	for r in opcode_idx {
		if r.count > max_bucket { max_bucket = r.count }
		if r.count > 0          { populated  += 1     }
	}
	fmt.printfln("OK -- %d entries across %d/256 opcode slots; max bucket = %d",
				 len(all), populated, max_bucket)
}

emit_header :: proc(sb: ^strings.Builder) {
	strings.write_string(sb, `package rexcode_mos65816

// =============================================================================
// GENERATED FILE - DO NOT EDIT
// =============================================================================
//
// Generated by tools/gen_decode_tables.odin from ENCODING_TABLE.
// Regenerate with:  cd mos65816 && odin run tools/gen_decode_tables.odin -file
//

Decode_Entry :: struct #packed {
	mnemonic: Mnemonic,
	ops:      [2]Operand_Type,
	enc:      [2]Operand_Encoding,
	opcode:   u8,
	length:   u8,
	flags:    Encoding_Flags,
}
#assert(size_of(Decode_Entry) == 9)

Decode_Index :: struct #packed {
	start: u16,
	count: u16,
}
#assert(size_of(Decode_Index) == 4)

`)
}

emit_entries :: proc(sb: ^strings.Builder, entries: []Entry) {
	fmt.sbprintfln(sb, "")
	fmt.sbprintfln(sb, "@(rodata)")
	fmt.sbprintfln(sb, "DECODE_ENTRIES := [%d]Decode_Entry{{", len(entries))
	for e in entries {
		flags_str := encode_flags_literal(e.flags)
		fmt.sbprintfln(sb,
			"\t{{ .%v, {{.%v, .%v}}, {{.%v, .%v}}, 0x%02X, %d, {{%s}} }},",
			e.mnemonic,
			e.ops[0], e.ops[1],
			e.enc[0], e.enc[1],
			e.opcode, e.length, flags_str)
	}
	strings.write_string(sb, "}\n")
}

encode_flags_literal :: proc(f: m.Encoding_Flags) -> string {
	sb: strings.Builder
	strings.builder_init(&sb)
	first := true
	write := proc(sb: ^strings.Builder, first: ^bool, s: string) {
		if !first^ { strings.write_string(sb, ", ") }
		strings.write_string(sb, s)
		first^ = false
	}
	if f.branch      { write(&sb, &first, "branch=true")      }
	if f.cond_branch { write(&sb, &first, "cond_branch=true") }
	if f.page_cross  { write(&sb, &first, "page_cross=true")  }
	return strings.to_string(sb)
}

emit_range_table :: proc(sb: ^strings.Builder, name: string, ranges: []Range) {
	fmt.sbprintfln(sb, "%s := [%d]Decode_Index{{", name, len(ranges))
	for r, i in ranges {
		if r.count == 0 {
			fmt.sbprintfln(sb, "\t/* %02X */ {{0, 0}},", i)
		} else {
			fmt.sbprintfln(sb, "\t/* %02X */ {{%d, %d}},", i, r.start, r.count)
		}
	}
	strings.write_string(sb, "}\n\n")
}
