package tests_issues

// CONTRIBUTORS:
//   If your test can be run normally with `odin test` and without extra build steps or custom compiler flags,
//   you can preferably add it here.
//   Otherwise, add it to `run.bat` and `run.sh`.

@(require) import "test_issue_829"
@(require) import "test_issue_1592"
@(require) import "test_issue_1730"
@(require) import "test_issue_2056"
@(require) import "test_issue_2466"
@(require) import "test_issue_2615"
@(require) import "test_issue_2637"
@(require) import "test_issue_2666"
@(require) import "test_issue_2694"
@(require) import "test_issue_3435"
@(require) import "test_issue_4210"
@(require) import "test_issue_4364"
@(require) import "test_issue_4584"
@(require) import "test_issue_5318"
@(require) import "test_issue_5699"
@(require) import "test_issue_6068"
@(require) import "test_issue_6165"
@(require) import "test_issue_6302"
@(require) import "test_issue_6419"
@(require) import "test_issue_6344"
@(require) import "test_issue_6396"
@(require) import "test_pr_6470"
@(require) import "test_issue_6753"
@(require) import "test_issue_6853"
@(require) import "test_issue_6951_5214"
@(require) import "test_issue_7008"
@(require) import "test_issue_7089"
@(require) import "test_issue_7316"
@(require) import "test_issue_7336"
@(require) import "test_issue_7356"
@(require) import "test_issue_7421"
@(require) import "test_issue_7430"
@(require) import "test_issue_7477_7506"
@(require) import "test_issue_7490"
@(require) import "test_issue_7547"
@(require) import "test_issue_7566"
@(require) import "test_issue_7587"
@(require) import "test_issue_7598"
@(require) import "test_issue_7700"
@(require) import "test_issue_7708"
@(require) import "test_issue_7779"
@(require) import "test_issue_fast_isel_lowering"
@(require) import "test_issue_omitted_field_union"
@(require) import "test_issue_equal_proc_dependencies"
@(require) import "test_issue_global_address_of_literal"
@(require) import "test_issue_bool_to_be_conversion"
@(require) import "test_issue_bool_comparison_truthiness"
@(require) import "test_issue_const_array_broadcast"
@(require) import "test_issue_decl_order"
@(require) import "test_issue_distinct_constraint"
@(require) import "test_issue_proc_constant_instantiation"
@(require) import "test_issue_swizzle_multi_assign"
@(require) import "test_issue_global_when_order"
@(require) import "test_issue_global_when_cycle_accepted"
@(require) import "test_issue_poly_using_subtype"
@(require) import "test_issue_global_proc_lits"
@(require) import "test_issue_packed_field_by_value"
@(require) import "test_issue_paren_poly_callee"
@(require) import "test_issue_procedure_of_specialized"

