// Procedures generated by the compiler: type equality, and later hashing and map access.
// They are local to the object and generated the first time they are referenced.

gb_internal xbProc *xb_new_proc(xbModule *m, String name, Type *type);
gb_internal void xb_lower_proc(xbProc *p);

gb_global PtrMap<Type *, i32> xb_equal_procs; // -1 while being generated, -2 if it cannot be

gb_internal xbMem xb_param_ptr_mem(xbProc *p, isize index) {
	Type *pt = base_type(p->type);
	Entity *e = pt->Proc.params->Tuple.variables[index];
	xbVar *v = map_get(&p->vars, e);
	GB_ASSERT(v != nullptr);
	u32 ptr = xb_load(p, xbType_I64, v->indirect ? xb_mem(xbMem_Reg, xb_load(p, xbType_I64, v->mem), 0) : v->mem);
	return xb_mem(xbMem_Reg, ptr, 0);
}

gb_internal void xb_ret_bool(xbProc *p, bool value) {
	xbMem r = xb_mem(xbMem_Local, cast(u32)p->ret_temp_local);
	xb_store(p, xbType_I8, r, xb_iconst(p, xbType_I8, value ? 1 : 0));
	xb_emit_ret(p, r);
}

gb_internal void xb_ret_bool_reg(xbProc *p, u32 value) {
	xbMem r = xb_mem(xbMem_Local, cast(u32)p->ret_temp_local);
	xb_store(p, xbType_I8, r, value);
	xb_emit_ret(p, r);
}

gb_internal void xb_equal_proc_body(xbProc *p, Type *type) {
	// both pointers are reloaded where needed, vregs do not cross blocks cheaply
	xbBlock *diff_ptr = xb_new_block(p);
	xbBlock *same_ptr = xb_new_block(p);
	{
		xbMem x = xb_param_ptr_mem(p, 0);
		xbMem y = xb_param_ptr_mem(p, 1);
		u32 same = xb_cmp(p, xbCond_EQ, xbType_I64, x.base, y.base);
		xb_branch(p, same, same_ptr, diff_ptr);
	}
	xb_start_block(p, same_ptr);
	xb_ret_bool(p, true);
	xb_start_block(p, diff_ptr);

	if (type->kind == Type_Struct) {
		type_set_offsets(type);
		xbBlock *block_false = xb_new_block(p);
		for_array(i, type->Struct.fields) {
			xbBlock *next = xb_new_block(p);
			Type *ft = nullptr;
			i64 off = type_offset_of(type, i, &ft);
			xbMem x = xb_param_ptr_mem(p, 0);
			xbMem y = xb_param_ptr_mem(p, 1);
			xbValue l = xb_load_value(p, ft, xb_mem_offset(x, off));
			xbValue r = xb_load_value(p, ft, xb_mem_offset(y, off));
			u32 ok = xb_value_to_reg(p, xb_emit_comp(p, Token_CmpEq, l, r));
			xb_branch(p, ok, next, block_false);
			xb_start_block(p, next);
		}
		xb_ret_bool(p, true);
		xb_start_block(p, block_false);
		xb_ret_bool(p, false);
	} else if (type->kind == Type_Union) {
		if (type_size_of(type) == 0) {
			xb_ret_bool(p, true);
		} else if (is_type_union_maybe_pointer(type)) {
			Type *v = type->Union.variants[0];
			xbMem x = xb_param_ptr_mem(p, 0);
			xbMem y = xb_param_ptr_mem(p, 1);
			u32 ok = xb_value_to_reg(p, xb_emit_comp(p, Token_CmpEq, xb_load_value(p, v, x), xb_load_value(p, v, y)));
			xb_ret_bool_reg(p, ok);
		} else {
			Type *tag_type = union_tag_type(type);
			xbType tt = xb_scalar_type(tag_type);
			i64 tag_off = type->Union.variant_block_size;
			xbBlock *block_false = xb_new_block(p);
			xbBlock *block_switch = xb_new_block(p);
			{
				xbMem x = xb_param_ptr_mem(p, 0);
				xbMem y = xb_param_ptr_mem(p, 1);
				u32 lt = xb_load(p, tt, xb_mem_offset(x, tag_off));
				u32 rt = xb_load(p, tt, xb_mem_offset(y, tag_off));
				xb_branch(p, xb_cmp(p, xbCond_EQ, tt, lt, rt), block_switch, block_false);
			}
			xb_start_block(p, block_switch);
			if (type->Union.kind != UnionType_no_nil) {
				xbBlock *case_block = xb_new_block(p);
				xbBlock *next = xb_new_block(p);
				xbMem x = xb_param_ptr_mem(p, 0);
				u32 lt = xb_load(p, tt, xb_mem_offset(x, tag_off));
				xb_branch(p, xb_cmp(p, xbCond_EQ, tt, lt, xb_iconst(p, tt, 0)), case_block, next);
				xb_start_block(p, case_block);
				xb_ret_bool(p, true);
				xb_start_block(p, next);
			}
			for (Type *v : type->Union.variants) {
				xbBlock *case_block = xb_new_block(p);
				xbBlock *next = xb_new_block(p);
				{
					xbMem x = xb_param_ptr_mem(p, 0);
					u32 lt = xb_load(p, tt, xb_mem_offset(x, tag_off));
					i64 tag = union_variant_index_checked(type, v);
					xb_branch(p, xb_cmp(p, xbCond_EQ, tt, lt, xb_iconst(p, tt, tag)), case_block, next);
				}
				xb_start_block(p, case_block);
				xbMem x = xb_param_ptr_mem(p, 0);
				xbMem y = xb_param_ptr_mem(p, 1);
				u32 ok = xb_value_to_reg(p, xb_emit_comp(p, Token_CmpEq, xb_load_value(p, v, x), xb_load_value(p, v, y)));
				xb_ret_bool_reg(p, ok);
				xb_start_block(p, next);
			}
			xb_jump(p, block_false);
			xb_start_block(p, block_false);
			xb_ret_bool(p, false);
		}
	} else {
		xbMem x = xb_param_ptr_mem(p, 0);
		xbMem y = xb_param_ptr_mem(p, 1);
		u32 ok = xb_value_to_reg(p, xb_emit_comp(p, Token_CmpEq, xb_load_value(p, type, x), xb_load_value(p, type, y)));
		xb_ret_bool_reg(p, ok);
	}
}

// The symbol of the equality procedure for `type`. Bails out of `caller` if it cannot be made.
gb_internal i32 xb_equal_proc_sym(xbProc *caller, Type *type) {
	xbModule *m = caller->m;
	type = base_type(type);
	i32 *found = map_get(&xb_equal_procs, type);
	if (found) {
		if (*found == -2) XB_UNSUPPORTED(caller, "equal procedure");
		if (*found >= 0) return *found;
		// -1: recursive, the symbol already exists
	}
	String name = lb_internal_gen_name_from_type("__$xb_equal", type);
	i32 sym = xb_symbol(m, name);
	if (found && *found == -1) return sym;
	m->symbols[sym].flags = xbSymbolFlag_Func; // local
	map_set(&xb_equal_procs, type, -1);

	xbProc *p = xb_new_proc(m, name, t_equal_proc);
	p->sym = sym;
	jmp_buf bail;
	p->bail = &bail;
	if (setjmp(bail) != 0) {
		map_set(&xb_equal_procs, type, -2);
		XB_UNSUPPORTED(caller, "equal procedure");
	}
	p->abi = xb_get_abi(p, t_equal_proc);
	xb_begin_proc(p);
	xb_equal_proc_body(p, type);
	xb_end_proc(p);
	xb_lower_proc(p);
	map_set(&xb_equal_procs, type, sym);
	return sym;
}

gb_internal xbValue xb_emit_record_equal(xbProc *p, TokenKind op, xbValue left, xbValue right, Type *type) {
	i32 sym = xb_equal_proc_sym(p, type);
	xbValue proc = xb_value_reg(t_equal_proc, xb_lea(p, xb_mem(xbMem_Sym, sym)));
	xbValue args[2] = {
		xb_value_reg(t_rawptr, xb_lea(p, xb_address_from_load_or_generate_local(p, left))),
		xb_value_reg(t_rawptr, xb_lea(p, xb_address_from_load_or_generate_local(p, right))),
	};
	xbValue res = xb_emit_call_internal(p, proc, sym, xb_args(args, 2));
	if (op == Token_NotEq) {
		res = xb_bool_not(p, res);
	}
	return res;
}

////////////////////////////////////////////////////////////////
// Hashers and map info
////////////////////////////////////////////////////////////////

gb_global PtrMap<Type *, i32> xb_hasher_procs; // -1 while being generated, -2 if it cannot be
gb_global PtrMap<Type *, i32> xb_map_infos;
gb_global PtrMap<Type *, i32> xb_map_cell_infos;

gb_internal i32 xb_hasher_proc_sym(xbProc *caller, Type *type);

gb_internal void xb_ret_uintptr(xbProc *p, u32 value) {
	xbMem r = xb_mem(xbMem_Local, cast(u32)p->ret_temp_local);
	xb_store(p, xbType_I64, r, value);
	xb_emit_ret(p, r);
}

// the data pointer and seed parameters of a hasher, reloaded where needed
gb_internal u32 xb_hasher_param(xbProc *p, isize index) {
	Type *pt = base_type(p->type);
	Entity *e = pt->Proc.params->Tuple.variables[index];
	xbVar *v = map_get(&p->vars, e);
	GB_ASSERT(v != nullptr && !v->indirect);
	return xb_load(p, xbType_I64, v->mem);
}

gb_internal u32 xb_call_hasher(xbProc *p, Type *type, u32 data, u32 seed) {
	i32 sym = xb_hasher_proc_sym(p, type);
	xbValue proc = xb_value_reg(t_hasher_proc, xb_lea(p, xb_mem(xbMem_Sym, cast(u32)sym)));
	xbValue args[2] = {xb_value_reg(t_rawptr, data), xb_value_reg(t_uintptr, seed)};
	return xb_value_to_reg(p, xb_emit_call_internal(p, proc, sym, xb_args(args, 2)));
}

gb_internal void xb_hasher_proc_body(xbProc *p, Type *type) {
	if (is_type_simple_compare(type)) {
		xbValue args[3] = {
			xb_value_reg(t_rawptr, xb_hasher_param(p, 0)),
			xb_value_reg(t_uintptr, xb_hasher_param(p, 1)),
			xb_value_reg(t_int, xb_iconst(p, xbType_I64, type_size_of(type))),
		};
		xbValue r = xb_emit_runtime_call(p, runtime_default_hasher_fixed_name(p->m->info), xb_args(args, 3));
		xb_ret_uintptr(p, xb_value_to_reg(p, r));
		return;
	}
	if (type->kind == Type_Struct) {
		type_set_offsets(type);
		xbMem seed_mem = xb_add_local(p, t_uintptr, false);
		xb_store(p, xbType_I64, seed_mem, xb_hasher_param(p, 1));
		for_array(i, type->Struct.fields) {
			Entity *field = type->Struct.fields[i];
			u32 data = xb_ptr_add_const(p, xb_hasher_param(p, 0), type->Struct.offsets[i]);
			u32 seed = xb_call_hasher(p, field->type, data, xb_load(p, xbType_I64, seed_mem));
			xb_store(p, xbType_I64, seed_mem, seed);
		}
		xb_ret_uintptr(p, xb_load(p, xbType_I64, seed_mem));
		return;
	}
	if (type->kind == Type_Union) {
		if (is_type_union_maybe_pointer(type)) {
			xb_ret_uintptr(p, xb_call_hasher(p, type->Union.variants[0], xb_hasher_param(p, 0), xb_hasher_param(p, 1)));
			return;
		}
		Type *tag_type = union_tag_type(type);
		xbType tt = xb_scalar_type(tag_type);
		for (Type *v : type->Union.variants) {
			xbBlock *case_block = xb_new_block(p);
			xbBlock *next = xb_new_block(p);
			u32 tag = xb_load(p, tt, xb_mem(xbMem_Reg, xb_hasher_param(p, 0), cast(i32)type->Union.variant_block_size));
			xb_branch(p, xb_cmp(p, xbCond_EQ, tt, tag, xb_iconst(p, tt, union_variant_index_checked(type, v))), case_block, next);
			xb_start_block(p, case_block);
			xb_ret_uintptr(p, xb_call_hasher(p, v, xb_hasher_param(p, 0), xb_hasher_param(p, 1)));
			xb_start_block(p, next);
		}
		xb_ret_uintptr(p, xb_hasher_param(p, 1));
		return;
	}
	if (type->kind == Type_Array || type->kind == Type_EnumeratedArray) {
		Type *elem = type->kind == Type_Array ? type->Array.elem : type->EnumeratedArray.elem;
		i64 count = type->kind == Type_Array ? type->Array.count : type->EnumeratedArray.count;
		i64 stride = type_size_of(elem);
		xbMem seed_mem = xb_add_local(p, t_uintptr, false);
		xb_store(p, xbType_I64, seed_mem, xb_hasher_param(p, 1));
		xbMem index_mem = xb_add_local(p, t_int, false);
		xb_store(p, xbType_I64, index_mem, xb_iconst(p, xbType_I64, 0));
		xbBlock *loop = xb_new_block(p);
		xbBlock *body = xb_new_block(p);
		xbBlock *done = xb_new_block(p);
		xb_jump(p, loop);
		xb_start_block(p, loop);
		xb_branch(p, xb_cmp(p, xbCond_SLT, xbType_I64, xb_load(p, xbType_I64, index_mem), xb_iconst(p, xbType_I64, count)), body, done);
		xb_start_block(p, body);
		u32 idx = xb_load(p, xbType_I64, index_mem);
		u32 data = xb_ptr_add_scaled(p, xb_hasher_param(p, 0), idx, stride);
		xb_store(p, xbType_I64, seed_mem, xb_call_hasher(p, elem, data, xb_load(p, xbType_I64, seed_mem)));
		xb_store(p, xbType_I64, index_mem, xb_binop(p, xbOp_Add, xbType_I64, xb_load(p, xbType_I64, index_mem), xb_iconst(p, xbType_I64, 1)));
		xb_jump(p, loop);
		xb_start_block(p, done);
		xb_ret_uintptr(p, xb_load(p, xbType_I64, seed_mem));
		return;
	}
	if (is_type_cstring(type) || is_type_string(type)) {
		// LLVM hashes a string16 with the string hasher too
		xbValue args[2] = {xb_value_reg(t_rawptr, xb_hasher_param(p, 0)), xb_value_reg(t_uintptr, xb_hasher_param(p, 1))};
		xbValue r = xb_emit_runtime_call(p, is_type_cstring(type) ? "default_hasher_cstring" : "default_hasher_string", xb_args(args, 2));
		xb_ret_uintptr(p, xb_value_to_reg(p, r));
		return;
	}
	if (is_type_float(type)) {
		xbValue v = xb_load_value(p, type, xb_mem(xbMem_Reg, xb_hasher_param(p, 0), 0));
		xbValue args[2] = {xb_emit_conv(p, v, t_f64), xb_value_reg(t_uintptr, xb_hasher_param(p, 1))};
		xbValue r = xb_emit_runtime_call(p, "default_hasher_f64", xb_args(args, 2));
		xb_ret_uintptr(p, xb_value_to_reg(p, r));
		return;
	}
	if (is_type_complex(type) || is_type_quaternion(type)) {
		// every part as an f64, in memory order
		Type *ft = base_complex_elem_type(type);
		i64 n = is_type_complex(type) ? 2 : 4;
		xbValue args[5] = {};
		for (i64 i = 0; i < n; i++) {
			xbValue part = xb_load_value(p, ft, xb_mem(xbMem_Reg, xb_hasher_param(p, 0), cast(i32)(i*type_size_of(ft))));
			args[i] = xb_emit_conv(p, part, t_f64);
		}
		args[n] = xb_value_reg(t_uintptr, xb_hasher_param(p, 1));
		xbValue r = xb_emit_runtime_call(p, n == 2 ? "default_hasher_complex128" : "default_hasher_quaternion256", xb_args(args, n+1));
		xb_ret_uintptr(p, xb_value_to_reg(p, r));
		return;
	}
	XB_UNSUPPORTED(p, "hasher type");
}

gb_internal i32 xb_hasher_proc_sym(xbProc *caller, Type *type) {
	xbModule *m = caller->m;
	type = core_type(type);
	i32 *found = map_get(&xb_hasher_procs, type);
	if (found) {
		if (*found == -2) XB_UNSUPPORTED(caller, "hasher procedure");
		if (*found >= 0) return *found;
	}
	String name = lb_internal_gen_name_from_type("__$xb_hasher", type);
	i32 sym = xb_symbol(m, name);
	if (found && *found == -1) return sym;
	m->symbols[sym].flags = xbSymbolFlag_Func;
	map_set(&xb_hasher_procs, type, -1);

	xbProc *p = xb_new_proc(m, name, t_hasher_proc);
	p->sym = sym;
	jmp_buf bail;
	p->bail = &bail;
	if (setjmp(bail) != 0) {
		map_set(&xb_hasher_procs, type, -2);
		XB_UNSUPPORTED(caller, "hasher procedure");
	}
	p->abi = xb_get_abi(p, t_hasher_proc);
	xb_begin_proc(p);
	xb_hasher_proc_body(p, type);
	xb_end_proc(p);
	xb_lower_proc(p);
	map_set(&xb_hasher_procs, type, sym);
	return sym;
}

// a constant Map_Cell_Info for the type
gb_internal i32 xb_map_cell_info_sym(xbModule *m, Type *type) {
	i32 *found = map_get(&xb_map_cell_infos, type);
	if (found) return *found;
	i64 size = 0, len = 0;
	map_cell_size_and_len(type, &size, &len);
	u64 values[4] = {cast(u64)type_size_of(type), cast(u64)type_align_of(type), cast(u64)size, cast(u64)len};
	i32 sym = xb_rodata(m, values, gb_size_of(values), 8);
	map_set(&xb_map_cell_infos, type, sym);
	return sym;
}

// a constant Map_Info: {key cell info, value cell info, hasher, equal}
gb_internal i32 xb_map_info_sym(xbProc *caller, Type *map_type) {
	xbModule *m = caller->m;
	map_type = base_type(map_type);
	i32 *found = map_get(&xb_map_infos, map_type);
	if (found) return *found;
	i32 ks = xb_map_cell_info_sym(m, map_type->Map.key);
	i32 vs = xb_map_cell_info_sym(m, map_type->Map.value);
	i32 hasher = xb_hasher_proc_sym(caller, map_type->Map.key);
	i32 equal = xb_equal_proc_sym(caller, map_type->Map.key);

	Array<u8> *data = &m->sections[xbSection_Data];
	while (data->count % 8 != 0) array_add(data, cast(u8)0);
	i64 at = data->count;
	for (int i = 0; i < 32; i++) array_add(data, cast(u8)0);
	i32 targets[4] = {ks, vs, hasher, equal};
	for (int i = 0; i < 4; i++) {
		xb_add_reloc(m, xbSection_Data, xbReloc_Abs64, at + 8*i, targets[i], 0);
	}
	char name[64] = {};
	gb_snprintf(name, gb_size_of(name), ".Lxb.map_info.%lld", cast(long long)at);
	i32 sym = xb_symbol(m, make_string_c(name));
	xbSymbol *s = &m->symbols[sym];
	s->section = xbSection_Data;
	s->offset = at;
	s->size = 32;
	s->flags = 0;
	map_set(&xb_map_infos, map_type, sym);
	return sym;
}

////////////////////////////////////////////////////////////////
// Map access through the runtime's generic procedures
////////////////////////////////////////////////////////////////

// hash and pointer of a key, for the map at `map_ptr`
gb_internal u32 xb_gen_map_key_hash(xbProc *p, u32 map_ptr, Type *map_type, xbValue key, u32 *key_ptr_) {
	Type *key_type = base_type(map_type)->Map.key;
	xbValue real_key = xb_emit_conv(p, key, key_type);
	u32 key_ptr = xb_lea(p, xb_address_from_load_or_generate_local(p, real_key));
	*key_ptr_ = key_ptr;
	// map_seed_from_map_data(data &~ (MAP_CACHE_LINE_SIZE-1))
	u32 data = xb_load(p, xbType_I64, xb_mem(xbMem_Reg, map_ptr, 0));
	u32 masked = xb_binop(p, xbOp_And, xbType_I64, data, xb_iconst(p, xbType_I64, cast(i64)~cast(u64)(MAP_CACHE_LINE_SIZE-1)));
	xbValue args[1] = {xb_value_reg(t_uintptr, masked)};
	xbValue seed = xb_emit_runtime_call(p, "map_seed_from_map_data", xb_args(args, 1));
	return xb_call_hasher(p, key_type, key_ptr, xb_value_to_reg(p, seed));
}

// a pointer to the value, or nil
gb_internal u32 xb_map_get_ptr(xbProc *p, u32 map_ptr, Type *map_type, xbValue key) {
	u32 key_ptr = 0;
	u32 hash = xb_gen_map_key_hash(p, map_ptr, map_type, key, &key_ptr);
	i32 info = xb_map_info_sym(p, map_type);
	xbValue args[4] = {
		xb_value_reg(t_raw_map_ptr, map_ptr),
		xb_value_reg(t_map_info_ptr, xb_lea(p, xb_mem(xbMem_Sym, cast(u32)info))),
		xb_value_reg(t_uintptr, hash),
		xb_value_reg(t_rawptr, key_ptr),
	};
	return xb_value_to_reg(p, xb_emit_runtime_call(p, "__dynamic_map_get", xb_args(args, 4)));
}

gb_internal void xb_map_set(xbProc *p, u32 map_ptr, Type *map_type, xbValue key, xbValue value, TokenPos pos) {
	map_type = base_type(map_type);
	u32 key_ptr = 0;
	u32 hash = xb_gen_map_key_hash(p, map_ptr, map_type, key, &key_ptr);
	xbValue v = xb_emit_conv(p, value, map_type->Map.value);
	u32 value_ptr = xb_lea(p, xb_address_from_load_or_generate_local(p, v));
	i32 info = xb_map_info_sym(p, map_type);
	String proc_name = p->entity ? p->entity->token.string : str_lit("");
	xbValue loc = xb_source_code_location(p, proc_name, pos);
	xbValue args[6] = {
		xb_value_reg(t_raw_map_ptr, map_ptr),
		xb_value_reg(t_map_info_ptr, xb_lea(p, xb_mem(xbMem_Sym, cast(u32)info))),
		xb_value_reg(t_uintptr, hash),
		xb_value_reg(t_rawptr, key_ptr),
		xb_value_reg(t_rawptr, value_ptr),
		loc,
	};
	xb_emit_runtime_call(p, "__dynamic_map_set", xb_args(args, 6));
}

// m[k], as the value or as (value, ok)
gb_internal xbValue xb_map_load(xbProc *p, xbAddr const &addr) {
	Type *map_type = base_type(addr.map_type);
	Type *lookup = map_type->Map.lookup_result_type;
	xbMem v = xb_add_local(p, lookup, true);
	u32 map_ptr = xb_load(p, xbType_I64, addr.mem);
	u32 ptr = xb_map_get_ptr(p, map_ptr, map_type, addr.map_key);
	u32 ok = xb_cmp(p, xbCond_NE, xbType_I64, ptr, xb_iconst(p, xbType_I64, 0));
	Type *ft = nullptr;
	xb_store(p, xbType_I8, xb_mem_offset(v, type_offset_of(lookup, 1, &ft)), ok);
	xbBlock *then_ = xb_new_block(p);
	xbBlock *done = xb_new_block(p);
	xb_branch(p, ok, then_, done);
	xb_start_block(p, then_);
	xb_memcopy(p, xb_mem_offset(v, type_offset_of(lookup, 0, &ft)), xb_mem(xbMem_Reg, ptr, 0), type_size_of(map_type->Map.value));
	xb_jump(p, done);
	xb_start_block(p, done);
	if (is_type_tuple(addr.map_result)) {
		return xb_value_mem(lookup, v);
	}
	return xb_load_value(p, map_type->Map.value, xb_mem_offset(v, type_offset_of(lookup, 0, &ft)));
}
